import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

type Vec3 = { x: number; y: number; z: number };

const createBoxSquare = (center: Vec3, gridSize: number, spacing: number): EnemyConfig[] => {
    const half = (gridSize - 1) / 2;
    const result: EnemyConfig[] = [];

    for (let ix = 0; ix < gridSize; ix++) {
        for (let iz = 0; iz < gridSize; iz++) {
            const isBorder = ix === 0 || iz === 0 || ix === gridSize - 1 || iz === gridSize - 1;

            if (!isBorder) continue;

            const x = center.x + (ix - half) * spacing;
            const z = center.z + (iz - half) * spacing;

            result.push({
                trigger: { pool: { self: 5, to_trigger: null } },
                enemy_type: "box",
                on_spawn: {
                    position: { x, y: center.y, z },
                    rotation_y: Math.PI,
                    hp: 2,
                    spawn_animation: false,
                    box: { w: 1.5, d: 1.5, h: 1.5 },
                },
                ground: {
                    id: 0,
                    physics: "plane",
                    size: SURFACE_SETTINGS.h,
                },
                is_inside_ground: false,
                follow_player: { enabled: false },
                triggers_by_player: [false, false],
                rotate_to_player: { enabled: false },
                auto_rotation: { enabled: false },
                animation: { enabled: false },
                shooter: { enabled: false },
            });
        }
    }

    return result;
};

export const enemies: EnemyConfig[] = [
    ...createBoxSquare({ x: 0, y: 5.65, z: 12.5 }, 4, 1.75),
    ...createBoxSquare({ x: 0, y: 5.65, z: -12.5 }, 4, 1.75),

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.75, y: 5.65, z: 12.8 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 10 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.75, y: 5.65, z: 12.8 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -10 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.75, y: 5.65, z: -12.8 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -10 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.75, y: 5.65, z: -12.8 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 10 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -13.75, y: 5.65, z: 15 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -8, y: 5.65, z: 15 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -13.75, y: 5.65, z: 12.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -8, y: 5.65, z: 12.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -13.75, y: 5.65, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -8, y: 5.65, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 13.75, y: 5.65, z: 15 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 8, y: 5.65, z: 15 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 13.75, y: 5.65, z: 12.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 8, y: 5.65, z: 12.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 13.75, y: 5.65, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 8, y: 5.65, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 20, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5.65, z: 0 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 100 },
    },
];
