server {
    listen 7777;
    server_name _;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
