import { WallConfig } from "types/static/Wall.types";

import { WALLS_COLOR } from "core_constants";
import { SURFACE_SETTINGS } from "./settings";

export const walls: WallConfig[] = [
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 11, y: 5.45, z: 0 },
        size: { w: 1.5, h: 1, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -11, y: 5.45, z: 0 },
        size: { w: 1.5, h: 1, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -33, y: 5.45, z: 0 },
        size: { w: 1.5, h: 1, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 33, y: 5.45, z: 0 },
        size: { w: 1.5, h: 1, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -6.8, y: 5.45, z: 0 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 6.8, y: 5.45, z: 0 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -6.8, y: 5.45, z: 13 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 6.8, y: 5.45, z: 13 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -6.8, y: 5.45, z: 26 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 6.8, y: 5.45, z: 26 },
        size: { w: 7, h: 1, d: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 52.5 },
        size: { w: SURFACE_SETTINGS.w, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -25 },
        size: { w: SURFACE_SETTINGS.w, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true }, dispose_pool: 50 },
        type: "box",
        position: { x: -2.4, y: 5.75, z: 24.6 },
        size: { w: 1.45, h: 1.45, d: 1.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true }, dispose_pool: 50 },
        type: "box",
        position: { x: -0.8, y: 5.75, z: 24.6 },
        size: { w: 1.45, h: 1.45, d: 1.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true }, dispose_pool: 50 },
        type: "box",
        position: { x: 0.8, y: 5.75, z: 24.6 },
        size: { w: 1.45, h: 1.45, d: 1.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true }, dispose_pool: 50 },
        type: "box",
        position: { x: 2.4, y: 5.75, z: 24.6 },
        size: { w: 1.45, h: 1.45, d: 1.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
];
