import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    //
    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 14.5, y: 5.75, z: -41.25 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1500,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: -14.5, y: 5.75, z: -41.25 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 1500,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 14.5, y: 5.75, z: -19.5 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 1500,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: -14.5, y: 5.75, z: -19.5 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 100,
            cooldown: 1500,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 22, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -36 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1500,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 22, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -24 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 1500,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 22, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 18, y: 5.75, z: -30 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 1500,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 22, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: -18, y: 5.75, z: -30 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: 1500,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -5, y: 5.75, z: -18.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 0, y: 5.75, z: -18.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 5, y: 5.75, z: -18.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -5, y: 5.75, z: -40.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 0, y: 5.75, z: -40.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 5, y: 5.75, z: -40.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 17.5, y: 5.75, z: -35 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 17.5, y: 5.75, z: -30 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 17.5, y: 5.75, z: -25 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -17.5, y: 5.75, z: -35 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -17.5, y: 5.75, z: -30 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -17.5, y: 5.75, z: -25 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 100, to_trigger: 1000 } },
        enemy_type: "rabbit",
        on_spawn: {
            position: { x: 0, y: 9, z: -30 },
            rotation_y: Math.PI,
            hp: 10,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.2 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: true, time: 0 },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 50,
            directions: generateDirections(20),
            spreading: 0.0001,
            pattern: [
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
                [1, 1, 5],
            ],
        },
    },
];
