import { WallConfig } from "types/static/Wall.types";

import { WALLS_COLOR } from "core_constants";
import { SURFACE_SETTINGS } from "./settings";
import { generateTree } from "utils/objects";

export const walls: WallConfig[] = [
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -72.5 },
        size: { w: SURFACE_SETTINGS.w, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -10, y: 5.45, z: -60 },
        size: { w: 2, h: 1, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 10, y: 5.45, z: -60 },
        size: { w: 2, h: 1, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    // arc
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -46 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: -46 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: -46 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: -46 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: -46 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: -46 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: -46 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: -46 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: -46 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    //arc

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -14 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: -14 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: -14 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: -14 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: -14 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: -14 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: -14 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: -14 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: -14 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 30 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: 30 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: 30 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: 30 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: 30 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: 30 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: 30 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: 30 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: 30 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 49.5 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: 49.5 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: 49.5 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: 49.5 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: 49.5 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: 49.5 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: 49.5 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: 49.5 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: 49.5 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 90 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: 90 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: 90 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: 90 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: 90 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: 90 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: 90 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: 90 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: 90 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 140 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -5, y: 5.45, z: 140 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 5, y: 5.45, z: 140 },
        size: { w: 1.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -10, y: 10.55, z: 140 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -5, y: 10.55, z: 140 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 10.55, z: 140 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 5, y: 10.55, z: 140 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 10, y: 10.55, z: 140 },
        size: { w: 0.5, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 16, z: 140 },
        size: { w: 22, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 26.85, y: 10.15, z: 148.5 },
        size: { w: 34.375, h: 10.5, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -26.85, y: 10.15, z: 148.5 },
        size: { w: 34.375, h: 10.5, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -36.23, y: 14.7, z: 114 },
        size: { w: 15.5, h: 19.5, d: 50 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 36.23, y: 14.7, z: 114 },
        size: { w: 15.5, h: 19.5, d: 50 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 26.7, y: 5.45, z: 90 },
        size: { w: 35.4, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -18.943, y: 5.45, z: 90 },
        size: { w: 19.885, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 19, y: 5.45, z: -47.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 29, y: 5.45, z: -42.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 36.5, y: 5.45, z: -30 },
        size: { w: 15, h: 1, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 29, y: 5.45, z: -17.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 19, y: 5.45, z: -12.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -19, y: 5.45, z: -47.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -29, y: 5.45, z: -42.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -36.5, y: 5.45, z: -30 },
        size: { w: 15, h: 1, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -29, y: 5.45, z: -17.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -19, y: 5.45, z: -12.5 },
        size: { w: 20, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -10, y: 5.45, z: 10 },
        size: { w: 2, h: 1, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 10, y: 5.45, z: 10 },
        size: { w: 2, h: 1, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 20.25, y: 7.95, z: -60 },
        size: { w: 17.5, h: 6, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -20.25, y: 7.95, z: -60 },
        size: { w: 17.5, h: 6, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 24.12, y: 7.95, z: -30 },
        size: { w: 9.25, h: 6, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -24.12, y: 7.95, z: -30 },
        size: { w: 9.25, h: 6, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 20, y: 8.95, z: 0 },
        size: { w: 17, h: 8, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 20, y: 9.95, z: 19.5 },
        size: { w: 17, h: 10, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -20, y: 8.95, z: 0 },
        size: { w: 17, h: 8, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -20, y: 9.95, z: 19.5 },
        size: { w: 17, h: 10, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -20, y: 10.95, z: 60 },
        size: { w: 17, h: 12, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -20, y: 11.95, z: 79.5 },
        size: { w: 17, h: 14, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 20, y: 10.95, z: 60 },
        size: { w: 17, h: 12, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 20, y: 11.95, z: 79.5 },
        size: { w: 17, h: 14, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -10, y: 5.45, z: 70.5 },
        size: { w: 2, h: 1, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 10, y: 5.45, z: 70.5 },
        size: { w: 2, h: 1, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -29, y: 5.45, z: 30 },
        size: { w: 40, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -29, y: 5.45, z: 49.5 },
        size: { w: 40, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -57.5, y: 11.95, z: 39.75 },
        size: { w: 17, h: 14, d: 21.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 37.75, y: 5.45, z: 30 },
        size: { w: 57.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 28.5, y: 5.45, z: 49.5 },
        size: { w: 39, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 75, y: 11.95, z: 39.75 },
        size: { w: 17, h: 14, d: 21.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 37.5, y: 9.95, z: 60 },
        size: { w: 17, h: 10, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 47, y: 5.45, z: 60.9 },
        size: { w: 2, h: 1, d: 21 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 59.5, y: 5.45, z: 49.5 },
        size: { w: 14, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 37.25, y: 5.45, z: 70.41 },
        size: { w: 17.5, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 29.5, y: 5.45, z: 73.14 },
        size: { w: 2, h: 1, d: 7.36 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 37, y: 9.95, z: 82.84 },
        size: { w: 17, h: 10, d: 12.25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 45.5, y: 5.45, z: 75.75 },
        size: { w: 34, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 53.513, y: 5.45, z: 60.966 },
        size: { w: 2, h: 1, d: 21 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 69, y: 9.95, z: 60 },
        size: { w: 29, h: 10, d: 19 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 53.93, y: 11.95, z: 82.84 },
        size: { w: 17, h: 14, d: 12.25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 75, y: 10.95, z: 82.84 },
        size: { w: 17, h: 12, d: 12.25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 67.97, y: 5.45, z: 70.5 },
        size: { w: 30.91, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 75, y: 11.95, z: 73.1 },
        size: { w: 17, h: 14, d: 7.2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 53.4, y: 5.45, z: 124.55 },
        size: { w: 18.1, h: 1, d: 71.48 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    // {
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     type: "box",
    //     position: { x: 96.95, y: 5.45, z: 191.75 },
    //     size: { w: 105.23, h: 1, d: 63.48 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: WALLS_COLOR,
    //     solid: true,
    //     is_lava: false,
    // },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 140.51, y: 5.45, z: 124.54 },
        size: { w: 18.1, h: 1, d: 71.48 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 116.37, y: 5.45, z: 58.91 },
        size: { w: 66.19, h: 1, d: 59.82 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 91.76, y: 10.95, z: 95 },
        size: { w: 17, h: 12, d: 12.25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 108.97, y: 12.45, z: 99.37 },
        size: { w: 17, h: 15, d: 21 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 124.52, y: 14.7, z: 124.36 },
        size: { w: 13.64, h: 19.5, d: 71 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 69.5, y: 14.7, z: 140 },
        size: { w: 13.64, h: 19.5, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 97, y: 11.95, z: 156.3 },
        size: { w: 41.5, h: 14, d: 7.2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 97, y: 5.95, z: 133 },
        size: { w: 3, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 94, y: 7.95, z: 129 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 100, y: 17.95, z: 129 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 91, y: 9.95, z: 133 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 103, y: 15.95, z: 133 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 94, y: 11.95, z: 137 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 100, y: 13.95, z: 137 },
        size: { w: 5, h: 2, d: 3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 20, z: 350 },
        size: { w: 50, h: 50, d: 50 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 40, z: 350 },
        size: { w: 40, h: 40, d: 40 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 60, z: 350 },
        size: { w: 30, h: 30, d: 30 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 80, z: 350 },
        size: { w: 20, h: 20, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 95, z: 350 },
        size: { w: 10, h: 10, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -9, y: 7, z: 275 },
        size: { w: 1.5, h: 10, d: 234 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 9, y: 7, z: 275 },
        size: { w: 1.5, h: 10, d: 234 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -47.5, y: 14.7, z: 69.75 },
        size: { w: 37, h: 19.5, d: 38.17 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -47.5, y: 8.85, z: 9.75 },
        size: { w: 37, h: 7.8, d: 38.17 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 56.35, y: 8.85, z: 9.86 },
        size: { w: 54.3, h: 7.8, d: 38.17 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    // trees
    ...generateTree({
        trunkPosition: { x: 12.5, y: 7, z: -30 },
    }),
    ...generateTree({
        trunkPosition: { x: -12.5, y: 7, z: -30 },
    }),

    // POOLS
    {
        trigger: { pool: 20, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 2.7, y: 5.45, z: -27.3 },
        size: { w: 5, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 10, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -2.7, y: 5.45, z: -32.7 },
        size: { w: 5, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 30, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 2.7, y: 5.45, z: -32.7 },
        size: { w: 5, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 40, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -2.7, y: 5.45, z: -27.3 },
        size: { w: 5, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 22, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: 2.5, y: 5.45, z: -46 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 22, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: -2.5, y: 5.45, z: -46 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 22, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: -7.45, y: 5.45, z: -46 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 22, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: 7.45, y: 5.45, z: -46 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 2.5, y: 5.45, z: -14 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -2.5, y: 5.45, z: -14 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -7.45, y: 5.45, z: -14 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 7.45, y: 5.45, z: -14 },
        size: { w: 3.125, h: 1, d: 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
];
