import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

type GenerateArrowEnemiesRowArgs = {
    z: number;
    delay?: number;
    reverse?: boolean;
};

const generateArrowEnemiesRow = ({
    z,
    delay = 0,
    reverse = false,
}: GenerateArrowEnemiesRowArgs): EnemyConfig[] => {
    const xs = reverse ? [5, 0, -5] : [-5, 0, 5];
    const spawnDuration = 1;
    const step = spawnDuration / xs.length;

    return xs.map((x, i) => ({
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x, y: 5.75, z },
            rotation_y: Math.PI,
            hp: 2,
            delay: +(delay + step * (i + 1)).toFixed(2),
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: {
                enabled: false,
                delay: [500, 100],
            },
            pattern: [[1, 1, 0]],
            spreading: 0.01,
            directions: [0],
        },
    }));
};

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: 0, y: 5.75, z: -20 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 2.5, y: 5.75, z: 10 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -2.5, y: 5.75, z: 10 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: 0, y: 5.75, z: 40 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 5, y: 5.75, z: 40 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -5, y: 5.75, z: 40 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
        shooter: { enabled: false },
    },
    //
    ...generateArrowEnemiesRow({ z: -40, delay: 0 }),
    ...generateArrowEnemiesRow({ z: -30, delay: 1, reverse: true }),
    ...generateArrowEnemiesRow({ z: -20, delay: 2 }),
    ...generateArrowEnemiesRow({ z: -10, delay: 3, reverse: true }),
    ...generateArrowEnemiesRow({ z: 10, delay: 4 }),
    ...generateArrowEnemiesRow({ z: 20, delay: 5, reverse: true }),
    ...generateArrowEnemiesRow({ z: 30, delay: 6 }),
    ...generateArrowEnemiesRow({ z: 30, delay: 8, reverse: true }),
    //
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 45 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -1.75, y: 5.75, z: 45 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 1.75, y: 5.75, z: 45 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -3.5, y: 5.75, z: 46 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 3.5, y: 5.75, z: 46 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -5.25, y: 5.75, z: 46 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 5.25, y: 5.75, z: 46 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 1.5, d: 0.75, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    //
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 60 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 1.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rage: {
            enabled: true,
            pool: 50,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(4),
            spreading: 0.0001,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [1, 0, 0],
                [0, 1, 0],
                [0, 1, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
    },
];
