import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const CHEER_PATTERN_RAGED: [number, number, number][] = Array(20).fill([1, 1, 0]);
const CHEER_PATTERN_FRIENDLY: [number, number, number][] = Array(20).fill([0, 0, 1]);

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    // 10
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 22, y: 5.75, z: 97 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -22, y: 5.75, z: 97 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 22, y: 5.75, z: 133 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -22, y: 5.75, z: 133 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 22, y: 5.75, z: 115 },
            rotation_y: -Math.PI / 2,
            hp: 1,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -22, y: 5.75, z: 115 },
            rotation_y: Math.PI / 2,
            hp: 1,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 133 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 11 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 97 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    // 20
    {
        trigger: { pool: { self: 20, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 5, y: 5.75, z: 70 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 20, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 70 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 500,
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 20, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -5, y: 5.75, z: 70 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },

    // 30
    {
        trigger: { pool: { self: 30, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -5, y: 5.45, z: 86.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.45, z: 86.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
            delay: 0.5,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 21 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 5, y: 5.45, z: 86.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    // 40
    {
        trigger: { pool: { self: 40, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 6, y: 5.45, z: -10.5 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 40, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.45, z: -10.5 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 40, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -6, y: 5.45, z: -10.5 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 40, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 3, y: 5.45, z: -5.5 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 40, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -3, y: 5.45, z: -5.5 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    // 50
    {
        trigger: { pool: { self: 50, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 6, y: 5.45, z: 10.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.45, z: 10.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -6, y: 5.45, z: 10.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 3, y: 5.45, z: 5.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 51 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -3, y: 5.45, z: 5.5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    // 60
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -7.5, y: 5.75, z: -25 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -25 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 7.5, y: 5.75, z: -25 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },

    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -7.5, y: 5.75, z: -30 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -30 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 7.5, y: 5.75, z: -30 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },

    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -7.5, y: 5.75, z: -35 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -35 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 7.5, y: 5.75, z: -35 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -5.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(250, 500),
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        is_miner: true,
    },

    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 5, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 10, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 15, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 3.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -5, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -10, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 60, to_trigger: 61 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -15, y: 5.75, z: -40 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
            delay: 3.0,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    //
    {
        trigger: { pool: { self: 100, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 0, y: 5.75, z: -67.5 }, rotation_y: 0, hp: 5 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 1.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 999 },
    },

    // TRAPS
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 20, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 28, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 36, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 20, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 28, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 36, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 81 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 45, y: 5.75, z: 39.75 },
            rotation_y: -Math.PI / 2,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -20, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -28, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -36, y: 5.75, z: 33.63 },
            rotation_y: 0,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -20, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -28, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -36, y: 5.75, z: 45.88 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
    {
        trigger: { pool: { self: 90, to_trigger: 91 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -45, y: 5.75, z: 39.75 },
            rotation_y: Math.PI / 2,
            hp: 1,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: { enabled: false },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },
];
