import { EnemyConfig } from "types/enemy/Enemies.types";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 6, y: 10.85, z: 0 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -6, y: 10.85, z: 0 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -4, y: 10.85, z: 2 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 4, y: 10.85, z: 2 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2, y: 10.85, z: 4 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2, y: 10.85, z: 4 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 10.85, z: 4 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 0, z: 0 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            cooldown_dynamic: [100, 100, 100, 100, 100, 750, 750, 750],
            directions: [0],
            spreading: 0.001,
            pattern: [[1, 1, 0]],
        },
        shield: { enabled: true, pool: 100 },
    },
];
