import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function createSphereEnemyConfig(
    position: EnemyConfig["on_spawn"]["position"],
    rotation_y: EnemyConfig["on_spawn"]["rotation_y"],
    pool: { self: number; to_trigger: number | null },
    shield_pool: number,
): EnemyConfig {
    return {
        trigger: { pool: pool },
        enemy_type: "sphere",
        on_spawn: {
            position,
            rotation_y,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: shield_pool },
    };
}

export const enemies: EnemyConfig[] = [
    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 1 },
        Math.PI,
        { self: 1, to_trigger: 10 },
        9,
    ),

    {
        trigger: { pool: { self: 11, to_trigger: 9 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 3 + 26.25 * 1 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 11, to_trigger: 9 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 8 + 26.25 * 1 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 11, to_trigger: 9 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 3 + 26.25 * 1 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 2 },
        Math.PI,
        { self: 2, to_trigger: 20 },
        19,
    ),
    {
        trigger: { pool: { self: 21, to_trigger: 19 } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 3 + 26.25 * 2 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -2.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },
    {
        trigger: { pool: { self: 21, to_trigger: 19 } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 8 + 26.25 * 2 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },
    {
        trigger: { pool: { self: 21, to_trigger: 19 } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 3 + 26.25 * 2 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 2.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 3 },
        Math.PI,
        { self: 3, to_trigger: 30 },
        29,
    ),
    {
        trigger: { pool: { self: 31, to_trigger: 29 } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 3 + 26.25 * 3 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 1.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 31, to_trigger: 29 } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 8 + 26.25 * 3 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 1.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 31, to_trigger: 29 } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 3 + 26.25 * 3 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 1.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 4 },
        Math.PI,
        { self: 4, to_trigger: 40 },
        39,
    ),
    {
        trigger: { pool: { self: 41, to_trigger: 39 } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 13 + 26.25 * 4 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -1.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 41, to_trigger: 39 } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 18 + 26.25 * 4 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },
    {
        trigger: { pool: { self: 41, to_trigger: 39 } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 13 + 26.25 * 4 },
            rotation_y: Math.PI,
            hp: 4,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: -1.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 2.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(900, 1100),
            cooldown: getRandomCooldown(900, 1100),
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
            spreading: 0.001,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
        },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 5 },
        Math.PI,
        { self: 5, to_trigger: 50 },
        49,
    ),
    {
        trigger: { pool: { self: 51, to_trigger: 49 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 3 + 26.25 * 5 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 2.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },
    {
        trigger: { pool: { self: 51, to_trigger: 49 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 8 + 26.25 * 5 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },
    {
        trigger: { pool: { self: 51, to_trigger: 49 } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 3 + 26.25 * 5 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -2.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: getRandomCooldown(2400, 2600) },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 6 },
        Math.PI,
        { self: 6, to_trigger: 60 },
        59,
    ),

    {
        trigger: { pool: { self: 61, to_trigger: 59 } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 8 + 26.25 * 6 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: {
            enabled: true,
            name: "bob",
            params: {
                axes: {
                    x: {
                        amplitude: 5,
                        speed: 60,
                    },
                },
                frames: 180,
            },
        },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 750,
            directions: [-Math.PI / 10, 0, Math.PI / 10],
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 7 },
        Math.PI,
        { self: 7, to_trigger: 70 },
        69,
    ),

    {
        trigger: { pool: { self: 71, to_trigger: 69 } },
        enemy_type: "sphere-bomb",
        on_spawn: {
            position: { x: 0, y: 5.65, z: -55 - 10 + 26.25 * 7 },
            rotation_y: Math.PI,
            hp: 5,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: {
            enabled: true,
            name: "bob",
            params: {
                axes: {
                    x: {
                        amplitude: 4,
                        speed: 45,
                    },
                    z: {
                        amplitude: 4,
                        speed: 90,
                    },
                },
                frames: 180,
            },
        },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 50,
            switch_shooter: { enabled: true, delay: [400, 1400] },
            directions: [-Math.PI / 10, 0, Math.PI / 10],
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        rocket_launcher: { enabled: true, cooldown: 800 },
    },

    //
    createSphereEnemyConfig(
        { x: 0, y: 5.75, z: -55 - 3 + 26.25 * 8 },
        Math.PI,
        { self: 8, to_trigger: 1000 },
        999,
    ),

    {
        trigger: { pool: { self: 81, to_trigger: 999 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -5, y: 5.65, z: -55 - 13 + 26.25 * 8 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: true,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: {
            enabled: true,
            name: "bob",
            params: {
                is_linear: true,
                axes: {
                    z: {
                        amplitude: 5,
                        speed: 60,
                    },
                },
                frames: 180,
            },
        },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 81, to_trigger: 999 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 5, y: 5.65, z: -55 - 13 + 26.25 * 8 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: true,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: {
            enabled: true,
            name: "bob",
            params: {
                is_linear: true,
                axes: {
                    z: {
                        amplitude: 5,
                        speed: 60,
                    },
                },
                frames: 180,
            },
        },
        shooter: { enabled: false },
        autoaimable: true,
    },
];
