import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -5, y: 10.85, z: 12 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -3, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 5, y: 10.85, z: 8.5 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 7, y: 10.85, z: 11 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 10, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 7, y: 10.85, z: 6.5 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 10, y: 10.85, z: 5.5 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 5, y: 10.85, z: -12 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 3, y: 10.85, z: -10 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -5, y: 10.85, z: -8.5 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -7, y: 10.85, z: -11 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -10, y: 10.85, z: -10 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -7, y: 10.85, z: -6.5 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -10, y: 10.85, z: -5.5 },
            rotation_y: 0,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(750, 1500),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -10, y: 10.85, z: 2.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 1000,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 10, y: 10.85, z: -2.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 1000,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -12, y: 10.85, z: 12 },
            rotation_y: Math.PI - Math.PI / 3,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 750],
            directions: generateDirections(2, Math.PI / 3),
            spreading: 0.0001,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 100 },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 12, y: 10.85, z: -12 },
            rotation_y: -Math.PI / 3,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 750],
            directions: generateDirections(2, Math.PI / 3),
            spreading: 0.0001,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 100 },
    },
];
