import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const CHEER_PATTERN_RAGED: [number, number, number][] = Array(20).fill([1, 1, 0]);
const CHEER_PATTERN_FRIENDLY: [number, number, number][] = Array(20).fill([0, 0, 1]);

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    // FIRST ROOM CHEERS
    {
        trigger: { pool: { self: 111, to_trigger: 800 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 22, y: 5.75, z: 97 }, rotation_y: 0, hp: 3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            spreading: 0.001,
            directions: generateDirections(10),
            pattern: CHEER_PATTERN_RAGED,
        },
    },
    {
        trigger: { pool: { self: 112, to_trigger: 810 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -22, y: 5.75, z: 97 }, rotation_y: 0, hp: 3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            spreading: 0.001,
            directions: generateDirections(10),
            pattern: CHEER_PATTERN_RAGED,
        },
    },
    {
        trigger: { pool: { self: 113, to_trigger: 820 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 22, y: 5.75, z: 133 }, rotation_y: 0, hp: 3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            spreading: 0.001,
            directions: generateDirections(10),
            pattern: CHEER_PATTERN_RAGED,
        },
    },
    {
        trigger: { pool: { self: 114, to_trigger: 830 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -22, y: 5.75, z: 133 }, rotation_y: 0, hp: 3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            spreading: 0.001,
            directions: generateDirections(10),
            pattern: CHEER_PATTERN_RAGED,
        },
    },

    // FIRST ROOM CORE
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 0, y: 5.75, z: 115 }, rotation_y: 0, hp: 5 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 50 },
        rage: {
            enabled: true,
            pool: 69,
            initial_delay: 250,
            cooldown: 250,
            spreading: 0.001,
            directions: generateDirections(10),
            pattern: CHEER_PATTERN_RAGED,
            switch_shooter: { enabled: true, delay: [500, 1500] },
        },
    },

    // 1ST BARRIER
    {
        trigger: { pool: { self: 710, to_trigger: 210 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 188 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["amusement_park_1"] },
        },
    },

    // 2ND BARRIER
    {
        trigger: { pool: { self: 720, to_trigger: 220 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 216 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["amusement_park_2"] },
        },
    },
    {
        trigger: { pool: { self: 720, to_trigger: 220 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2, y: 5.75, z: 218 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 720, to_trigger: 220 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2, y: 5.75, z: 218 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // 3RD BARRIER
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 244 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["amusement_park_3"] },
        },
    },
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2, y: 5.75, z: 246 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2, y: 5.75, z: 246 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 248 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1000,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -4, y: 5.75, z: 248 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 730, to_trigger: 230 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 4, y: 5.75, z: 248 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // 4TH BARRIER
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 272 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["amusement_park_4"] },
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2, y: 5.75, z: 274 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2, y: 5.75, z: 274 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 5.75, z: 276 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1000,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -4, y: 5.75, z: 276 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 4, y: 5.75, z: 276 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -6, y: 5.75, z: 278 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2, y: 5.75, z: 278 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2, y: 5.75, z: 278 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 740, to_trigger: 240 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 6, y: 5.75, z: 278 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // 5TH BARRIER
    {
        trigger: { pool: { self: 750, to_trigger: 250 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -6, y: 5.75, z: 308 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1000,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["amusement_park_5"] },
        },
    },
    {
        trigger: { pool: { self: 750, to_trigger: 250 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -3, y: 5.75, z: 308 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 750, to_trigger: 250 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 0, y: 5.75, z: 308 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 750, to_trigger: 250 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 3, y: 5.75, z: 308 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 750,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 750, to_trigger: 250 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 6, y: 5.75, z: 308 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 200,
            cooldown: 1000,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // FINAL CORE
    {
        trigger: { pool: { self: 998, to_trigger: 999 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -5, y: 6.25, z: 320 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: false,
            box: { w: 2.5, d: 2.5, h: 2.5 },
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 998, to_trigger: 999 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 5, y: 6.25, z: 320 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: false,
            box: { w: 2.5, d: 2.5, h: 2.5 },
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 100, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 0, y: 5.75, z: 320 }, rotation_y: 0, hp: 5 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 1.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 999 },
    },
];
