import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -1.5, y: 10.85, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 0, y: 10.85, z: 7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 1.5, y: 10.85, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7.5, y: 10.85, z: 3.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 7.5, y: 10.85, z: 3.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -10, y: 10.85, z: 0 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 50 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 10, y: 10.85, z: 0 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 7.5, y: 10.85, z: 0 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 6.5, y: 10.85, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 9.5, y: 10.85, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7, y: 10.85, z: 7 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 50, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7, y: 10.85, z: -1 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -12, y: 10.85, z: 12 },
            rotation_y: Math.PI - Math.PI / 3,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 750],
            directions: generateDirections(2, Math.PI / 3),
            spreading: 0.0001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 50, rotate_to_player_pool: 50 },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 12, y: 10.85, z: -12 },
            rotation_y: -Math.PI / 3,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: 100,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 750],
            directions: generateDirections(2, Math.PI / 3),
            spreading: 0.0001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        rage: {
            enabled: true,
            pool: 100,
            initial_delay: 1,
            cooldown: 100,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2, Math.PI / 3),
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 50, rotate_to_player_pool: 50 },
    },
];
