import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const HEIGHT = 0.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const ZERO_PATTERN: [number, number, number][] = Array(20).fill([0, 0, 1]);

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 10, to_trigger: 500 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 0, y: 1, z: 25 }, rotation_y: Math.PI, hp: 25, spawn_animation: false },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        metadata: { sister: "five" },
        scale_hp_by_difficulty: false,
        sounds: {
            on_damage: { engine: "enemy", sound: ["zero_reflected"] },
        },
        autoaimable: false,
    },
    {
        trigger: { pool: { self: 20, to_trigger: 500 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 23.775, y: 1, z: 7.725 }, rotation_y: Math.PI, hp: 25, spawn_animation: false },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        metadata: { sister: "four" },
        scale_hp_by_difficulty: false,
        sounds: {
            on_damage: { engine: "enemy", sound: ["enemy_damage"] },
        },
        autoaimable: false,
    },
    {
        trigger: { pool: { self: 30, to_trigger: 500 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 14.695, y: 1, z: -20.225 }, rotation_y: Math.PI, hp: 25, spawn_animation: false },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        metadata: { sister: "three" },
        scale_hp_by_difficulty: false,
        sounds: {
            on_damage: { engine: "enemy", sound: ["enemy_damage"] },
        },
        autoaimable: false,
    },
    {
        trigger: { pool: { self: 40, to_trigger: 500 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: -14.695, y: 1, z: -20.225 }, rotation_y: Math.PI, hp: 25, spawn_animation: false },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        metadata: { sister: "two" },
        scale_hp_by_difficulty: false,
        sounds: {
            on_damage: { engine: "enemy", sound: ["enemy_damage"] },
        },
        autoaimable: false,
    },
    {
        trigger: { pool: { self: 50, to_trigger: 500 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: -23.775, y: 1, z: 7.725 }, rotation_y: Math.PI, hp: 25, spawn_animation: false },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
        metadata: { sister: "one" },
        scale_hp_by_difficulty: false,
        sounds: {
            on_damage: { engine: "enemy", sound: ["enemy_damage"] },
        },
        autoaimable: false,
    },

    //
    {
        trigger: { pool: { self: 60, to_trigger: 1000 } },
        enemy_type: "zero",
        on_spawn: {
            position: { x: 0, y: 1, z: 0 },
            rotation_y: Math.PI,
            hp: 125,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false, angular_speed: 2 * Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            pattern: ZERO_PATTERN,
            spreading: 0.001,
            directions: generateDirections(10),
        },
        shield: { enabled: true, pool: 666 },
        change_behavior: { auto_rotation_pool: 500 },
    },
];
