import { LightConfig } from "types/engine/Light.types";

export const light: LightConfig[] = [
    {
        type: "spot",
        name: "zero-light",
        intensity: 0.9,
        position: { x: 0, y: 31, z: 0 },
        target: { x: 0, y: -10, z: 0 },
        castShadow: true,
        shadowType: "static",
    },
    {
        type: "directional",
        name: "aboveground-for-dynamic-objects",
        intensity: 0.001,
        position: { x: 0, y: 105, z: 0 },
        target: { x: 0, y: -1, z: 0 },
        castShadow: true,
        shadowType: "dynamic",
    },
    {
        type: "directional",
        name: "aboveground",
        intensity: 0.075,
        position: { x: 0, y: 10, z: 0 },
        target: { x: 0, y: -1, z: 0 },
        castShadow: false,
        shadowType: "static",
    },
    {
        type: "directional",
        name: "side-z-plus",
        intensity: 0.4,
        position: { x: 0, y: 10, z: 0 },
        target: { x: 0, y: 0, z: 1 },
        castShadow: false,
        shadowType: "static",
    },
    {
        type: "directional",
        name: "side-z-minus",
        intensity: 0.4,
        position: { x: 0, y: 10, z: 0 },
        target: { x: 0, y: 0, z: -1 },
        castShadow: false,
        shadowType: "static",
    },
    {
        type: "directional",
        name: "side-x-plus",
        intensity: 0.4,
        position: { x: 0, y: 10, z: 0 },
        target: { x: 1, y: 0, z: 0 },
        castShadow: false,
        shadowType: "static",
    },
    {
        type: "directional",
        name: "side-x-minus",
        intensity: 0.4,
        position: { x: 0, y: 10, z: 0 },
        target: { x: -1, y: 0, z: 0 },
        castShadow: false,
        shadowType: "static",
    },
];
