import { WallConfig } from "types/static/Wall.types";
import { SURFACE_SETTINGS } from "./settings";

export const walls: WallConfig[] = [
    {
        type: "cylinder-invisible",
        position: { x: 0, y: 0, z: 0 },
        size: { w: SURFACE_SETTINGS.w + 0.5, h: 20, d: SURFACE_SETTINGS.w + 0.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    // {
    //     type: "cylinder-base",
    //     position: { z: 25, y: 0, x: 0 },
    //     size: { w: 10, h: 0.5, d: 10 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 1, g: 0, b: 0, a: 1 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: false,
    //     is_lava: false,
    // },
    {
        type: "cylinder-transparent",
        position: { z: 25, y: 5.5, x: 0 },
        size: { w: 10, h: 10.5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 1, g: 0, b: 0, a: 1 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    // {
    //     type: "cylinder-base",
    //     position: { z: 7.725, y: 0, x: 23.775 },
    //     size: { w: 10, h: 0.5, d: 10 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 1, b: 0, a: 1 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: false,
    //     is_lava: false,
    // },
    {
        type: "cylinder-transparent",
        position: { z: 7.725, y: 5.5, x: 23.775 },
        size: { w: 10, h: 10.5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 1, g: 0, b: 0, a: 1 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    // {
    //     type: "cylinder-base",
    //     position: { z: -20.225, y: 0, x: 14.695 },
    //     size: { w: 10, h: 0.5, d: 10 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 0, b: 1, a: 1 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: false,
    //     is_lava: false,
    // },
    {
        type: "cylinder-transparent",
        position: { z: -20.225, y: 5.5, x: 14.695 },
        size: { w: 10, h: 10.5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 1, g: 0, b: 0, a: 1 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    // {
    //     type: "cylinder-base",
    //     position: { z: -20.225, y: 0, x: -14.695 },
    //     size: { w: 10, h: 0.5, d: 10 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 1, g: 1, b: 0, a: 1 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: false,
    //     is_lava: false,
    // },
    {
        type: "cylinder-transparent",
        position: { z: -20.225, y: 5.5, x: -14.695 },
        size: { w: 10, h: 10.5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 1, g: 0, b: 0, a: 1 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    // {
    //     type: "cylinder-base",
    //     position: { z: 7.725, y: 0, x: -23.775 },
    //     size: { w: 10, h: 0.5, d: 10 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 1, g: 0, b: 1, a: 1 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: false,
    //     is_lava: false,
    // },
    {
        type: "cylinder-transparent",
        position: { z: 7.725, y: 5.5, x: -23.775 },
        size: { w: 10, h: 10.5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 1, g: 0, b: 0, a: 1 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },
];
