import { EnemyConfig } from "types/enemy/Enemies.types";

const HEIGHT = 1;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getDynamicCooldown(length: number = 24) {
    const cooldowns = [];

    for (let i = 0; i < length; i++) {
        cooldowns.push(i * 100);
    }

    return cooldowns;
}

export const enemies: EnemyConfig[] = [
    // Cylinders
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.5, y: 1.25, z: -11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.5, y: 1.25, z: -11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.5, y: 1.25, z: 11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.5, y: 1.25, z: 11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.5, y: -1.25, z: -11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: false },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -13.5, y: -1.25, z: 11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: false },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.5, y: -1.25, z: -11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: false },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 13.5, y: -1.25, z: 11 }, rotation_y: Math.PI, hp: 3 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: false },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },

    //
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -5, y: 1, z: 3 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 7.5, y: 1, z: 4 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 3.5, y: 1, z: -1 }, rotation_y: Math.PI, hp: 2, delay: 5.0 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 3.5, y: 1, z: 1 }, rotation_y: Math.PI, hp: 2, delay: 6.0 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 3.5, y: 1, z: 0 },
            rotation_y: Math.PI,
            hp: 2,
            delay: 11.33,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -9, y: 1, z: 6 }, rotation_y: Math.PI, hp: 2, delay: 11.66 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 9, y: 1, z: 6 }, rotation_y: Math.PI, hp: 2, delay: 11.0 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    //
    //

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7.5, y: -1, z: -4 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -3.5, y: -1, z: -7 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -3.5, y: -1, z: 1 },
            rotation_y: 0,
            hp: 2,
            delay: 5.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -3.5, y: -1, z: -1 },
            rotation_y: 0,
            hp: 2,
            delay: 6.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -3.5, y: -1, z: -0 },
            rotation_y: 0,
            hp: 2,
            delay: 10.33,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -3, y: -1, z: -6 }, rotation_y: 0, hp: 2, delay: 10.66 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 3, y: -1, z: -6 }, rotation_y: 0, hp: 2, delay: 12.0 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5, z: 0 },
            rotation_y: Math.PI,
            hp: 12,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 100,
            cooldown_dynamic: getDynamicCooldown(),
            switch_shooter: { enabled: true, delay: [750, 750] },
            directions: [0],
            spreading: 0.0001,
            pattern: [[1, 1, 0]],
        },
        rage: {
            enabled: true,
            pool: 100,
            initial_delay: 750,
            cooldown: 357.14285714285714285714285714286,
            directions: [0],
            spreading: 0.0001,
            pattern: [[1, 1, 0]],
        },
        shield: { enabled: true, pool: 100 },
        scale_hp_by_difficulty: false,
    },

    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5, z: 0 },
            rotation_y: 0,
            hp: 12,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: true,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, true],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 100,
            cooldown_dynamic: getDynamicCooldown(),
            switch_shooter: { enabled: true, delay: [750, 750] },
            directions: [0],
            spreading: 0.0001,
            pattern: [[1, 1, 0]],
        },
        rage: {
            enabled: true,
            pool: 100,
            initial_delay: 750,
            cooldown: 357.14285714285714285714285714286,
            directions: [0],
            spreading: 0.0001,
            pattern: [[1, 1, 0]],
        },
        shield: { enabled: true, pool: 100 },
        scale_hp_by_difficulty: false,
    },
];
