import { WallConfig } from "types/static/Wall.types";
import { SURFACE_SETTINGS } from "./settings";

export const walls: WallConfig[] = [
    {
        type: "box-invisible",
        position: { x: 0, y: 0, z: 13 },
        size: { w: SURFACE_SETTINGS.w + 10, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 0, y: 0, z: -13 },
        size: { w: SURFACE_SETTINGS.w + 10, h: 10, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    {
        type: "box-invisible",
        position: { x: 15.5, y: 0, z: 0 },
        size: { w: 1, h: 10, d: SURFACE_SETTINGS.d + 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -15.5, y: 0, z: 0 },
        size: { w: 1, h: 10, d: SURFACE_SETTINGS.d + 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
    },

    //
    {
        type: "box",
        position: { x: -11, y: 1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: 11, y: 1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: -5.5, y: 1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: 5.5, y: 1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    // {
    //     type: "box",
    //     position: { x: 0, y: 1.25, z: 4.5 },
    //     size: { w: 1.5, h: 1.5, d: 1.5 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 0, b: 0, a: 0 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: true,
    //     is_lava: true,
    //     not_cast_shadow: true,
    // },
    // {
    //     type: "box",
    //     position: { x: 0, y: 1.25, z: 12 },
    //     size: { w: 1.5, h: 1.5, d: 1.5 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 0, b: 0, a: 0 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: true,
    //     is_lava: true,
    //     not_cast_shadow: true,
    // },

    {
        type: "box",
        position: { x: -11, y: -1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: 11, y: -1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: -5.5, y: -1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    {
        type: "box",
        position: { x: 5.5, y: -1.25, z: 0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: true,
        not_cast_shadow: true,
    },
    // {
    //     type: "box",
    //     position: { x: 0, y: -1.25, z: -4.5 },
    //     size: { w: 1.5, h: 1.5, d: 1.5 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 0, b: 0, a: 0 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: true,
    //     is_lava: true,
    //     not_cast_shadow: true,
    // },
    // {
    //     type: "box",
    //     position: { x: 0, y: -1.25, z: -12 },
    //     size: { w: 1.5, h: 1.5, d: 1.5 },
    //     rotation: { x: 0, y: 0, z: 0 },
    //     color: { r: 0, g: 0, b: 0, a: 0 },
    //     trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
    //     solid: true,
    //     is_lava: true,
    //     not_cast_shadow: true,
    // },
];
