import { EnemyConfig } from "types/enemy/Enemies.types";

const HEIGHT = 0.5;

export const SISTERS_CONFIG: EnemyConfig[] = [
    {
        trigger: { pool: { self: 10, to_trigger: 100 } },
        enemy_type: "sphere",
        scale_hp_by_difficulty: false,
        on_spawn: { position: { x: 0, y: 1, z: 25 }, rotation_y: Math.PI, hp: 10 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 65535 },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 200 } },
        enemy_type: "sphere",
        scale_hp_by_difficulty: false,
        on_spawn: { position: { x: 23.775, y: 1, z: 7.725 }, rotation_y: Math.PI, hp: 10 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 100 },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 300 } },
        enemy_type: "sphere",
        scale_hp_by_difficulty: false,
        on_spawn: { position: { x: 14.695, y: 1, z: -20.225 }, rotation_y: Math.PI, hp: 10 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 200 },
    },
    {
        trigger: { pool: { self: 40, to_trigger: 400 } },
        enemy_type: "sphere",
        scale_hp_by_difficulty: false,
        on_spawn: { position: { x: -14.695, y: 1, z: -20.225 }, rotation_y: Math.PI, hp: 10 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 300 },
    },
    {
        trigger: { pool: { self: 50, to_trigger: 500 } },
        enemy_type: "sphere",
        scale_hp_by_difficulty: false,
        on_spawn: { position: { x: -23.775, y: 1, z: 7.725 }, rotation_y: Math.PI, hp: 10 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 400 },
    },
];
