import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -5, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7.5, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -10, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 5, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 7.5, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 20 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 10, y: 10.85, z: -7.5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 5, to_trigger: 21 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 15, y: 10.85, z: -5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 20 },
        change_behavior: { follow_player_pool: 20 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },
    {
        trigger: { pool: { self: 5, to_trigger: 21 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 10.85, z: -5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 20 },
        change_behavior: { follow_player_pool: 20 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },
    {
        trigger: { pool: { self: 5, to_trigger: 21 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -15, y: 10.85, z: -5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 20 },
        change_behavior: { follow_player_pool: 20 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },

    //
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -5, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -7.5, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -10, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 5, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 7.5, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 30, to_trigger: 40 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 10, y: 10.85, z: 7.5 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 31, to_trigger: 41 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 15, y: 10.85, z: 17.5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        rage: {
            pool: 40,
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 40 },
        change_behavior: { follow_player_pool: 40 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },
    {
        trigger: { pool: { self: 31, to_trigger: 41 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -15, y: 10.85, z: 17.5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        rage: {
            pool: 40,
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 40 },
        change_behavior: { follow_player_pool: 40 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 10.85, z: 17.5 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            cooldown_dynamic: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000],
            directions: generateDirections(2),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 2, 0],
                [2, 1, 0],
                [2, 2, 0],
            ],
        },
        shield: { enabled: true, pool: 41 },
        change_behavior: { follow_player_pool: 41 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1", "robovoice_2", "robovoice_3", "robovoice_4", "robovoice_5", "robovoice_6"] },
        },
    },
];
