import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    //
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 4, y: 10.85, z: -4 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: true,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "sphere-bomb",
        on_spawn: {
            position: { x: -5, y: 10.85, z: 8 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: {
            position: { x: 5, y: 10.85, z: 1 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: true,
            delay: 3.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 9, y: 10.85, z: -3 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: true,
            delay: 4.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: -8, y: 10.85, z: 5 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: true,
            delay: 5.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 6, y: 10.85, z: 2 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 6.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -1, y: 10.85, z: 6 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 7.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "rocket",
        on_spawn: {
            position: { x: 2, y: 10.85, z: 0 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: false,
            delay: 8.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 7.5 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 5 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -7, y: 10.85, z: -7 },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: true,
            delay: 9.0,
            box: { w: 1.5, h: 1.5, d: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "cheer",
        on_spawn: {
            position: { x: 10, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 10.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "kamikaze",
        on_spawn: {
            position: { x: -3, y: 10.85, z: -5 },
            rotation_y: Math.PI,
            hp: 1,
            spawn_animation: true,
            delay: 11.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 15 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            pattern: [
                [1, 1, 1],
                [1, 1, 1],
            ],
            spreading: 0.001,
            directions: generateDirections(1, Math.PI / 2),
        },
        sounds: {
            on_spawn: { engine: "voice", sound: ["kamikaze_scream_1", "kamikaze_scream_2", "kamikaze_scream_3", "kamikaze_scream_4", "kamikaze_scream_5", "kamikaze_scream_6"] },
            while_alive: { engine: "enemy", sound: ["kamikaze_alarm"] },
        },
    },

    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -10, y: 10.85, z: 7 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 12.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [[1, 1, 1]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 5, y: 10.85, z: -4 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 13.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [[1, 1, 1]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 100, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 9, y: 10.85, z: 1 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 14.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 750,
            cooldown: 750,
            pattern: [[1, 1, 1]],
            spreading: 0.001,
            directions: [0],
        },
    },

    //
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -5, y: 10.85, z: 0 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 6, y: 10.85, z: -1 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 1, y: 10.85, z: 9 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 3.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -9, y: 10.85, z: 2 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 4.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -4, y: 10.85, z: -7 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 5.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 3, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 6.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -3, y: 10.85, z: -10 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 7.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -6, y: 10.85, z: -8 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 8.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: -8, y: 10.85, z: 4 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 9.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 200, to_trigger: null } },
        enemy_type: "arrow-shield",
        on_spawn: {
            position: { x: 8, y: 10.85, z: 7 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: true,
            delay: 10.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            pattern: [[0, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    //
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 9, y: 10.85, z: -1 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 1.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 2000 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 4, y: 10.85, z: -4 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 2.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1900 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: -7, y: 10.85, z: -2 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 3.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1800 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 8, y: 10.85, z: 5 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 4.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1700 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 0, y: 10.85, z: 4 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 5.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1600 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 6, y: 10.85, z: -8 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 6.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1500 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: -6, y: 10.85, z: -9 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 7.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1400 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 2, y: 10.85, z: -3 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 8.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1300 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: -5, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 9.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1200 },
    },
    {
        trigger: { pool: { self: 300, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: {
            position: { x: 7, y: 10.85, z: -10 },
            rotation_y: Math.PI,
            hp: 4,
            spawn_animation: false,
            delay: 10.0,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: Math.PI },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1100 },
    },
    //

    {
        trigger: { pool: { self: 900, to_trigger: 1000 } },
        enemy_type: "manah",
        on_spawn: {
            position: { x: 0, y: 10.85, z: 0 },
            rotation_y: Math.PI,
            hp: 13,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 0 },
        auto_rotation: { enabled: true, angular_speed: 0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            disabled_on_start: true,
            initial_delay: 250,
            cooldown: 50,
            directions: generateDirections(8),
            spreading: 0.0001,
            switch_shooter: { enabled: true, delay: [167, 750] },
            pattern: [
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
                [1, 2, 3],
            ],
        },
        shield: { enabled: true, pool: 65535 },
    },
];
