import { WallConfig } from "types/static/Wall.types";

import { WALLS_COLOR } from "core_constants";
import { SURFACE_SETTINGS } from "./settings";

import { generateTree } from "utils/objects";

export const walls: WallConfig[] = [
    // "scene"
    ...generateTree({ trunkPosition: { x: -20, y: 8.5, z: 35 } }),
    ...generateTree({ trunkPosition: { x: 20, y: 8.5, z: 35 } }),

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-invisible",
        position: { x: 0, y: 6, z: 39.75 },
        size: { w: 72, h: 2, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 0, y: 9, z: 44.75 },
        size: { w: 72, h: 3, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-base",
        position: { x: 0, y: 13, z: 44.75 },
        size: { w: 72, h: 4, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 0, y: 18, z: 44.75 },
        size: { w: 72, h: 5, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    // layers
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 6, z: -29 },
        size: { w: 10, h: 2, d: 10 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -31, y: 6, z: 2.875 },
        size: { w: 10, h: 2, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 31, y: 6, z: 2.875 },
        size: { w: 10, h: 2, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: 31, y: 9, z: 2.875 },
        size: { w: 10, h: 3, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-base",
        position: { x: 31, y: 13, z: 2.875 },
        size: { w: 10, h: 4, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: 31, y: 18, z: 2.875 },
        size: { w: 10, h: 5, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-dark",
        position: { x: -31, y: 9, z: 2.875 },
        size: { w: 10, h: 3, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-base",
        position: { x: -31, y: 13, z: 2.875 },
        size: { w: 10, h: 4, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box-ui",
        position: { x: -31, y: 18, z: 2.875 },
        size: { w: 10, h: 5, d: 73.75 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 6.5, y: 6, z: -27.75 },
        size: { w: 3, h: 2, d: 12.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 9.5, y: 6, z: -26.5 },
        size: { w: 3, h: 2, d: 15 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 12.5, y: 6, z: -25.25 },
        size: { w: 3, h: 2, d: 17.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 15.5, y: 6, z: -24 },
        size: { w: 3, h: 2, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 18.5, y: 6, z: -22.75 },
        size: { w: 3, h: 2, d: 22.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 21.5, y: 6, z: -21.5 },
        size: { w: 3, h: 2, d: 25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 24.5, y: 6, z: -20.25 },
        size: { w: 3, h: 2, d: 27.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    //
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -6.5, y: 6, z: -27.75 },
        size: { w: 3, h: 2, d: 12.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -9.5, y: 6, z: -26.5 },
        size: { w: 3, h: 2, d: 15 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -12.5, y: 6, z: -25.25 },
        size: { w: 3, h: 2, d: 17.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -15.5, y: 6, z: -24 },
        size: { w: 3, h: 2, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -18.5, y: 6, z: -22.75 },
        size: { w: 3, h: 2, d: 22.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -21.5, y: 6, z: -21.5 },
        size: { w: 3, h: 2, d: 25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -24.5, y: 6, z: -20.25 },
        size: { w: 3, h: 2, d: 27.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
];
