import { ChapterLabel, versesLayout } from "./verseProgression";

/**
 * Hand-maintained list of the music that must be decoded before any verse of a chapter starts.
 *
 * Deliberately not derived from the verse `music.ts` configs: boss tracks are referenced from the
 * boss logic instead of the level config, so they can only be listed explicitly. Every path here
 * must also exist in `public/sounds/music/list_main.json`, which supplies the loop/one-shot
 * settings used when the sound is created.
 */
export const chapterMusic: Readonly<Record<ChapterLabel, readonly string[]>> = {
    "◼ CHAPTER  01": [
        "sounds/music/00-10/Game/bass/8_bit/full/Pascal.ogg",
        "sounds/music/00-10/Game/bass/8_bit/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/bass/original/full/Pascal.ogg",
        "sounds/music/00-10/Game/bass/original/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/drums/8_bit/full/Pascal.ogg",
        "sounds/music/00-10/Game/drums/8_bit/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/drums/original/full/Pascal.ogg",
        "sounds/music/00-10/Game/drums/original/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/instruments/8_bit/full/Pascal.ogg",
        "sounds/music/00-10/Game/instruments/8_bit/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/instruments/original/full/Pascal.ogg",
        "sounds/music/00-10/Game/instruments/original/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/vocals/8_bit/full/Pascal.ogg",
        "sounds/music/00-10/Game/vocals/8_bit/one_shot/Pascal.ogg",
        "sounds/music/00-10/Game/vocals/original/full/Pascal.ogg",
        "sounds/music/00-10/Game/vocals/original/one_shot/Pascal.ogg",
    ],
    "◼ CHAPTER  02": [
        "sounds/music/11-21/Game/bass/8_bit/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/bass/8_bit/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/bass/original/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/bass/original/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/drums/8_bit/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/drums/8_bit/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/drums/original/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/drums/original/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/instruments/8_bit/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/instruments/8_bit/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/instruments/original/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/instruments/original/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/vocals/8_bit/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/vocals/8_bit/one_shot/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/vocals/original/full/End_Of_The_Unknown.ogg",
        "sounds/music/11-21/Game/vocals/original/one_shot/End_Of_The_Unknown.ogg",
    ],
    "◼ CHAPTER  03": [
        "sounds/music/22-32/Game/bass/8_bit/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/bass/8_bit/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/bass/original/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/bass/original/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/drums/8_bit/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/drums/8_bit/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/drums/original/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/drums/original/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/instruments/8_bit/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/instruments/8_bit/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/instruments/original/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/instruments/original/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/vocals/8_bit/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/vocals/8_bit/one_shot/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/vocals/original/full/Dark_Colossus.ogg",
        "sounds/music/22-32/Game/vocals/original/one_shot/Dark_Colossus.ogg",
    ],
    "◼ CHAPTER  04": [
        "sounds/music/33-43/Game/bass/8_bit/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/bass/8_bit/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/bass/original/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/bass/original/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/drums/8_bit/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/drums/8_bit/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/drums/original/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/drums/original/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/instruments/8_bit/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/instruments/8_bit/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/instruments/original/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/instruments/original/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/vocals/8_bit/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/vocals/8_bit/one_shot/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/vocals/original/full/Possessed_By_Disease.ogg",
        "sounds/music/33-43/Game/vocals/original/one_shot/Possessed_By_Disease.ogg",
    ],
    "◼ CHAPTER  05": [
        "sounds/music/44-54/Game/bass/8_bit/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/bass/8_bit/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/bass/original/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/bass/original/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/drums/8_bit/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/drums/8_bit/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/drums/original/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/drums/original/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/instruments/8_bit/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/instruments/8_bit/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/instruments/original/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/instruments/original/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/vocals/8_bit/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/vocals/8_bit/one_shot/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/vocals/original/full/Dependent_Weakling.ogg",
        "sounds/music/44-54/Game/vocals/original/one_shot/Dependent_Weakling.ogg",
    ],
    "◼ CHAPTER   I": [
        "sounds/music/55-58/Game/bass/8_bit/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/bass/8_bit/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/bass/original/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/bass/original/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/drums/8_bit/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/drums/8_bit/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/drums/original/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/drums/original/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/instruments/8_bit/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/instruments/8_bit/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/instruments/original/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/instruments/original/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/vocals/8_bit/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/vocals/8_bit/one_shot/Amusement_Park.ogg",
        "sounds/music/55-58/Game/vocals/original/full/Amusement_Park.ogg",
        "sounds/music/55-58/Game/vocals/original/one_shot/Amusement_Park.ogg",
        // verse 59 — Simone, also referenced from SimoneMusicConfig.ts
        "sounds/music/59-59/Game/bass/8_bit/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/bass/8_bit/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/bass/original/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/bass/original/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/drums/8_bit/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/drums/8_bit/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/drums/original/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/drums/original/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/instruments/8_bit/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/instruments/8_bit/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/instruments/original/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/instruments/original/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/vocals/8_bit/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/vocals/8_bit/one_shot/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/vocals/original/full/A_Beautiful_Song.ogg",
        "sounds/music/59-59/Game/vocals/original/one_shot/A_Beautiful_Song.ogg",
    ],
    "◼ CHAPTER  II": [
        // verses 61, 60, 63 and Shadowlord (verse 64), also in ShadowlordMusicConfig.ts
        "sounds/music/61-63/Game/bass/8_bit/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/bass/8_bit/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/bass/original/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/bass/original/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/drums/8_bit/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/drums/8_bit/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/drums/original/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/drums/original/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/instruments/8_bit/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/instruments/8_bit/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/instruments/original/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/instruments/original/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/vocals/8_bit/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/vocals/8_bit/one_shot/Shadowlord.ogg",
        "sounds/music/61-63/Game/vocals/original/full/Shadowlord.ogg",
        "sounds/music/61-63/Game/vocals/original/one_shot/Shadowlord.ogg",
        // verse 62
        "sounds/music/62-62/Game/bass/8_bit/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/bass/8_bit/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/bass/original/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/bass/original/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/drums/8_bit/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/drums/8_bit/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/drums/original/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/drums/original/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/instruments/8_bit/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/instruments/8_bit/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/instruments/original/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/instruments/original/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/vocals/8_bit/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/vocals/8_bit/one_shot/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/vocals/original/full/Dance_Of_The_Evanescent.ogg",
        "sounds/music/62-62/Game/vocals/original/one_shot/Dance_Of_The_Evanescent.ogg",
    ],
    "◼ CHAPTER III": [
        "sounds/music/65-65/Game/instruments/8_bit/full/Galgaliel.ogg",
        "sounds/music/65-65/Game/instruments/original/full/Galgaliel.ogg",
        "sounds/music/66-66/Game/instruments/8_bit/full/Zophiel.ogg",
        "sounds/music/66-66/Game/instruments/original/full/Zophiel.ogg",
        "sounds/music/67-67/Game/instruments/8_bit/full/Almisael.ogg",
        "sounds/music/67-67/Game/instruments/original/full/Almisael.ogg",
        "sounds/music/68-68/Game/instruments/8_bit/full/Egregori.ogg",
        "sounds/music/68-68/Game/instruments/original/full/Egregori.ogg",
        "sounds/music/69-69/Game/instruments/8_bit/full/Abdiel.ogg",
        "sounds/music/69-69/Game/instruments/original/full/Abdiel.ogg",
        // verse 71 — Zero, hardcoded in Zero.ts, absent from the verse config
        "sounds/music/71-71/Game/instruments/8_bit/full/Final_Song.ogg",
        "sounds/music/71-71/Game/instruments/8_bit/one_shot/Final_Song.ogg",
    ],
    "◼ CHAPTER  IV": [
        "sounds/music/72-76/Game/instruments/original/full/Impatience.ogg",
        "sounds/music/72-76/Game/instruments/original/one_shot/Impatience.ogg",
        "sounds/music/76-76/Game/instruments/original/full/Impatience-2.ogg",
        // verse 77 — Manah, hardcoded in Manah.ts, absent from the verse config
        "sounds/music/77-77-1/Game/instruments/8_bit/full/Fate.ogg",
        "sounds/music/77-77-1/Game/instruments/8_bit/one_shot/Fate.ogg",
        "sounds/music/77-77-1/Game/instruments/original/full/Fate.ogg",
        "sounds/music/77-77-1/Game/instruments/original/one_shot/Fate.ogg",
        "sounds/music/77-77-2/Game/vocals/8_bit/full/Fate.ogg",
        "sounds/music/77-77-2/Game/vocals/original/full/Fate.ogg",
    ],
    "◼ CHAPTER   V": [
        "sounds/music/78/Game/instruments/original/full/Durka_Raz.ogg",
        "sounds/music/79/Game/instruments/original/full/Durka_Dva.ogg",
        "sounds/music/80/Game/instruments/original/full/Durka_Tri.ogg",
        "sounds/music/81/Game/instruments/original/full/Durka_Chetiry.ogg",
        "sounds/music/82/Game/instruments/original/full/Durka_Five.ogg",
        // verse 83 — Queen, hardcoded in Queen.ts, absent from the verse config
        "sounds/music/83/Game/instruments/original/full/Queen.ogg",
    ],
};

/**
 * Tracks that stay decoded for the whole session. The menu plays the track of whichever verse is
 * highlighted, so these are needed before a chapter is ever picked and must survive every unload.
 */
export const alwaysResidentMusic: readonly string[] = [
    "sounds/music/Menu/1.ogg",
    "sounds/music/Menu/2.ogg",
    "sounds/music/Menu/3.ogg",
    "sounds/music/Menu/4.ogg",
    "sounds/music/Menu/5.ogg",
];

const chapterLabels = Object.keys(versesLayout) as ChapterLabel[];

export const getChapterForVerse = (verseId: string): ChapterLabel | null =>
    chapterLabels.find((chapter) => versesLayout[chapter].includes(verseId)) ?? null;

export const getChapterMusicPaths = (chapter: ChapterLabel): readonly string[] =>
    chapterMusic[chapter];
