import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const createBoxLine = (
    z: number,
    xOffset: number = 0,
    xPositions: number[] = [-0.88, -2.63, 0.88, 2.63],
): EnemyConfig[] => {
    const wh = 1.5;

    return xPositions.map((x) => ({
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: x + xOffset, y: 5.75, z },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: false,
            box: { w: wh, d: 0.75, h: wh },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    }));
};

export const enemies: EnemyConfig[] = [
    ...createBoxLine(-16, 22.75),
    ...createBoxLine(-14.5, 22.75),
    ...createBoxLine(-13, 22.75),

    ...createBoxLine(-16, 7),
    ...createBoxLine(-14.5, 7),
    ...createBoxLine(-13, 7),

    ...createBoxLine(-16, -8.75),
    ...createBoxLine(-14.5, -8.75),
    ...createBoxLine(-13, -8.75),

    ...createBoxLine(-3.5, -23.625, [-1.75, 0, 1.75]),
    ...createBoxLine(7, -23.625, [-1.75, 0, 1.75]),
    ...createBoxLine(17.5, -23.625, [-1.75, 0, 1.75]),

    // Right room

    {
        trigger: { pool: { self: 1, to_trigger: 15 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 18.38, y: 5.65, z: 1.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 1, to_trigger: 15 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 25.38, y: 5.65, z: 1.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 1, to_trigger: 15 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 21.88, y: 5.65, z: 1.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: 10 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 21.88, y: 5.65, z: 6.375 },
            rotation_y: Math.PI,
            hp: 5,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            directions: [-Math.PI / 2, -Math.PI / 4, 0, Math.PI / 4, Math.PI / 2],
            spreading: 0.0001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 15 },
    },

    // center room
    {
        trigger: { pool: { self: 3, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 8.75, y: 5.65, z: -8.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 3, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 7, y: 5.65, z: -8.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 3, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: 5.25, y: 5.65, z: -8.75 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    // left room
    {
        trigger: { pool: { self: 4, to_trigger: 30 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -12.25, y: 5.65, z: 1.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 4, to_trigger: 30 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -5.25, y: 5.65, z: 1.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 6, to_trigger: 20 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -8.75, y: 5.65, z: 6.375 },
            rotation_y: Math.PI,
            hp: 5,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 1000,
            directions: [0],
            spreading: 0.0001,
            pattern: [[1, 1, 0]],
        },
        shield: { enabled: true, pool: 30 },
    },

    // barrier
    {
        trigger: { pool: { self: 7, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -23.63, y: 5.65, z: -7 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 8, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -23.63, y: 5.65, z: 3.5 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 9, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -23.63, y: 5.65, z: 13 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    // final room
    {
        trigger: { pool: { self: 80, to_trigger: 100 } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: -17.7, y: 5.65, z: 31.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 100 } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: -29.56, y: 5.65, z: 31.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -27.12, y: 5.65, z: 28 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 80, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: {
            position: { x: -20.12, y: 5.65, z: 28 },
            rotation_y: Math.PI,
            hp: 2,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 90, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -23.63, y: 5.65, z: 32.5 },
            rotation_y: Math.PI,
            hp: 5,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 500,
            directions: generateDirections(2),
            spreading: 0.0001,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
    },
];
