import { WallConfig } from "types/static/Wall.types";

import { WALLS_COLOR } from "core_constants";

const DEFAULT_BOX_SIZE = 1.5;
export function generateWallFromPattern({
    pattern,
    center,
    type = "box",
    step = 1.75,
    rotationY = Math.PI,
    boxSize = { w: DEFAULT_BOX_SIZE, h: DEFAULT_BOX_SIZE, d: DEFAULT_BOX_SIZE },
    baseConfig = {
        rotation: { x: 0, y: 0, z: 0 },
        solid: true,
        disable_physics: true,
    },
    isLava = false,
    pools = [0],
    state = { on_start: true, on_update: false },
}: {
    pattern: string[];
    center: { x: number; y: number; z: number };
    type?: string;
    step?: number;
    rotationY?: number;
    boxSize?: { w: number; h: number; d: number };
    baseConfig?: any;
    isLava?: boolean;
    pools?: number[];
    state?: { on_start: boolean; on_update: boolean };
}) {
    const result: any[] = [];

    const rows = pattern.length;
    const cols = Math.max(...pattern.map((r) => r.length));

    const offsetX = (cols - 1) * step * 0.5;
    const offsetZ = (rows - 1) * step * 0.5;

    const cos = Math.cos(rotationY);
    const sin = Math.sin(rotationY);

    for (let row = 0; row < rows; row++) {
        for (let col = 0; col < pattern[row].length; col++) {
            if (pattern[row][col] !== "*") continue;

            const localX = col * step - offsetX;
            const localZ = row * step - offsetZ;

            const rotatedX = localX * cos - localZ * sin;
            const rotatedZ = localX * sin + localZ * cos;

            result.push({
                ...baseConfig,
                type: type,
                position: {
                    x: center.x + rotatedX,
                    y: center.y,
                    z: center.z + rotatedZ,
                },
                trigger: {
                    pool: pools[0],
                    spawn: state,
                    dispose_pool: pools[1],
                },
                size: boxSize,
                is_lava: isLava,
            });
        }
    }

    return result;
}

export const walls: WallConfig[] = [
    {
        type: "box-invisible",
        position: { x: 30.625, y: 5.45, z: -36.85 },
        size: { w: 8.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -0.11, y: 5.45, z: -24.55 },
        size: { w: 55.79, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 30.625, y: 5.45, z: -15.67 },
        size: { w: 8.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 14.875, y: 5.45, z: -15.67 },
        size: { w: 8.45, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -0.875, y: 5.45, z: -15.67 },
        size: { w: 8.45, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -16.6, y: 5.45, z: -15.67 },
        size: { w: 8.45, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -16.6, y: 5.45, z: 17.4 },
        size: { w: 8.45, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -30.65, y: 5.45, z: 17.4 },
        size: { w: 8.45, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -14.875, y: 5.45, z: -3.55 },
        size: { w: 4.87, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -2.65, y: 5.45, z: -3.55 },
        size: { w: 4.87, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 16.63, y: 5.45, z: -5.3 },
        size: { w: 4.87, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 28.08, y: 5.45, z: -5.3 },
        size: { w: 3.3, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -8.75, y: 5.45, z: 8.82 },
        size: { w: 17.17, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 21.8, y: 5.45, z: 8.82 },
        size: { w: 17.17, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 7, y: 5.45, z: -5.15 },
        size: { w: 10.37, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -23.63, y: 5.45, z: 36.88 },
        size: { w: 22.62, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },

    {
        type: "box-invisible",
        position: { x: -34.22, y: 5.45, z: 27.1 },
        size: { w: 1.5, h: 1.5, d: 20.8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -13, y: 5.45, z: 27.1 },
        size: { w: 1.5, h: 1.5, d: 20.8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -27.2, y: 5.45, z: -3.57 },
        size: { w: 1.5, h: 1.5, d: 40.6 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -20.02, y: 5.45, z: 0.15 },
        size: { w: 1.5, h: 1.5, d: 33.15 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -16.72, y: 5.45, z: 2.63 },
        size: { w: 1.5, h: 1.5, d: 13.84 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -0.75, y: 5.45, z: 2.63 },
        size: { w: 1.5, h: 1.5, d: 13.84 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -13.19, y: 5.45, z: -9.72 },
        size: { w: 1.5, h: 1.5, d: 13.43 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: -4.3, y: 5.45, z: -9.72 },
        size: { w: 1.5, h: 1.5, d: 13.43 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 2.55, y: 5.45, z: -10.47 },
        size: { w: 1.5, h: 1.5, d: 9.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 11.45, y: 5.45, z: -10.47 },
        size: { w: 1.5, h: 1.5, d: 9.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 18.31, y: 5.45, z: -10.47 },
        size: { w: 1.5, h: 1.5, d: 9.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 27.21, y: 5.45, z: -10.47 },
        size: { w: 1.5, h: 1.5, d: 9.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 14.8, y: 5.45, z: 1.25 },
        size: { w: 1.5, h: 1.5, d: 13.84 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 28.92, y: 5.45, z: 1.25 },
        size: { w: 1.5, h: 1.5, d: 13.84 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 27.04, y: 5.45, z: -30.95 },
        size: { w: 1.5, h: 1.5, d: 12.33 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box-invisible",
        position: { x: 34.2, y: 5.45, z: -26.5 },
        size: { w: 1.5, h: 1.5, d: 21.25 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },

    ...generateWallFromPattern({
        pattern: [
            "                           *************",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *           *",
            "                           *****   *****",
            "                               *   *    ",
            "                               *   *    ",
            "                               *   *    ",
            "                               *   *    ",
            "   *********        ********** *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        *        * *   *    ",
            "   *       *        ***    *** *   *    ",
            "   **    *** ******   *    *   *   *    ",
            "    *    *   *    *   *    *   *   *    ",
            "    *    *   *    *   *    *   *   *    ",
            "    *    *   *    *   *    *   *   *    ",
            "    *    *   *    *   *    *   *   *    ",
            "    *    *   *    *   *    *   *   *    ",
            "*****    *****    *****    *****   *    ",
            "*                                  *    ",
            "*                                  *    ",
            "*                                  *    ",
            "*                                  *    ",
            "*   ********************************    ",
            "*   *                                   ",
            "*   *                                   ",
            "*   *                                   ",
            "*   *                                   ",
            "*   *                                   ",
            "*   *                                   ",
            "*****                                   ",
        ],
        center: { x: 0, y: 5.75, z: 0 },
        isLava: true,
    }),

    //

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 40.25 },
        size: { w: 125, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -40.25 },
        size: { w: 125, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -37.5, y: 5.45, z: 0 },
        size: { w: 5, h: 1, d: 125 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 37.5, y: 5.45, z: 0 },
        size: { w: 5, h: 1, d: 125 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -31.75, y: 5.45, z: -10.7 },
        size: { w: 7.5, h: 1, d: 54.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -1.964, y: 5.45, z: -31.97 },
        size: { w: 56.24, h: 1, d: 12.93 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -16.63, y: 5.45, z: -9.61 },
        size: { w: 5, h: 1, d: 10.3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -0.88, y: 5.45, z: -9.61 },
        size: { w: 5, h: 1, d: 10.3 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 14.88, y: 5.45, z: -10.5 },
        size: { w: 5, h: 1, d: 8.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 31.61, y: 5.45, z: -10.5 },
        size: { w: 7, h: 1, d: 8.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -18.38, y: 5.45, z: 6 },
        size: { w: 1.5, h: 1, d: 21 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 13.13, y: 5.45, z: 15.75 },
        size: { w: 1.5, h: 1, d: 45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0.84, y: 5.45, z: -6.13 },
        size: { w: 1.57, h: 1, d: 5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 24.06, y: 5.45, z: 24.03 },
        size: { w: 22.72, h: 1, d: 28.57 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 32.75, y: 5.45, z: 0 },
        size: { w: 6, h: 1, d: 20.31 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //

    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0.43, y: 5.45, z: 23.9 },
        size: { w: 25.1, h: 1, d: 28.53 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 6.4, y: 5.45, z: 3.01 },
        size: { w: 12.67, h: 1, d: 14.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -14.79, y: 5.45, z: 13.07 },
        size: { w: 6.48, h: 1, d: 6.87 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        disable_physics: true,
    },

    //
    {
        type: "box",
        position: { x: -21.88, y: 5.45, z: -15.75 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 10, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box",
        position: { x: -23.63, y: 5.45, z: -15.75 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 10, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box",
        position: { x: -25.38, y: 5.45, z: -15.75 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 10, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box",
        position: { x: -21.88, y: 5.45, z: -14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 20, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box",
        position: { x: -23.63, y: 5.45, z: -14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 20, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },
    {
        type: "box",
        position: { x: -25.38, y: 5.45, z: -14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 20, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
    },

    {
        type: "box",
        position: { x: -21.88, y: 5.45, z: 14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 40, spawn: { on_start: false, on_update: true } },
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        type: "box",
        position: { x: -23.63, y: 5.45, z: 14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 40, spawn: { on_start: false, on_update: true } },
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        type: "box",
        position: { x: -25.38, y: 5.45, z: 14.0 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        trigger: { pool: 40, spawn: { on_start: false, on_update: true } },
        solid: true,
        is_lava: false,
        effective: true,
    },
];
