import { WallConfig } from "types/static/Wall.types";

import { SURFACE_SETTINGS } from "./settings";

export const walls: WallConfig[] = [
    // platform
    {
        type: "box-base",
        position: { x: 0, y: 4, z: 0 },
        size: { w: SURFACE_SETTINGS.w, h: 2, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
        animation: {
            name: "spline",
            spline: ["z:20", "x:20", "z:40", "x:-20", "z:20"],
            frames: 120,
            speed: 2,
            loop: false,
        },
    },

    {
        type: "box-invisible",
        position: { x: 0, y: 0.5, z: 0.6 },
        size: { w: SURFACE_SETTINGS.w + 2, h: 2, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        parent_name: "barrier-box-base-0",
    },
    {
        type: "box-invisible",
        position: { x: 0, y: 0.5, z: -0.6 },
        size: { w: SURFACE_SETTINGS.w + 2, h: 2, d: 1 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        parent_name: "barrier-box-base-0",
    },
    {
        type: "box-invisible",
        position: { x: 0.6, y: 0.5, z: 0 },
        size: { w: 1, h: 2, d: SURFACE_SETTINGS.d + 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        parent_name: "barrier-box-base-0",
    },
    {
        type: "box-invisible",
        position: { x: -0.6, y: 0.5, z: 0 },
        size: { w: 1, h: 2, d: SURFACE_SETTINGS.d + 2 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        parent_name: "barrier-box-base-0",
    },

    // walls
    {
        type: "box-dark",
        position: { x: -15, y: 4, z: 40 },
        size: { w: 10, h: 8, d: 85 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },
    {
        type: "box-dark",
        position: { x: 35, y: 4, z: 40 },
        size: { w: 10, h: 8, d: 85 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },

    {
        type: "box-dark",
        position: { x: 20, y: 4, z: 3.725 },
        size: { w: 20, h: 8, d: 12.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },
    {
        type: "box-dark",
        position: { x: 20, y: 4, z: 76.275 },
        size: { w: 20, h: 8, d: 12.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },

    {
        type: "box-dark",
        position: { x: 0, y: 4, z: 40 },
        size: { w: 20, h: 8, d: 20 },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: true,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },

    //
    {
        type: "box-base",
        position: { x: 0, y: 4, z: 90 },
        size: { w: SURFACE_SETTINGS.w, h: 2, d: SURFACE_SETTINGS.d },
        rotation: { x: 0, y: 0, z: 0 },
        color: { r: 0, g: 0, b: 0, a: 0 },
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        solid: false,
        is_lava: false,
        disable_physics: true,
        not_mergeable: true,
    },
];
