import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function createArrowEnemyConfig(
    x: number,
    z: number,
    rotation_y: number,
    pool: number,
): EnemyConfig {
    return {
        trigger: {
            pool: {
                self: pool,
                to_trigger: 100,
            },
        },
        enemy_type: "arrow",
        on_spawn: {
            position: {
                x: x,
                y: 5.75,
                z: z,
            },
            rotation_y: rotation_y,
            hp: 2,
        },
        ground: {
            id: 0,
            physics: "plane",
            size: 10,
        },
        is_inside_ground: false,
        follow_player: {
            enabled: true,
            speed: 2.0,
        },
        triggers_by_player: [true, false],
        rotate_to_player: {
            enabled: true,
            angular_speed: 2,
        },
        auto_rotation: {
            enabled: false,
        },
        animation: {
            enabled: false,
        },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: {
                enabled: false,
                delay: [500, 100],
            },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    };
}

export const enemies: EnemyConfig[] = [
    // STATIC
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 6.5, y: 5.75, z: 10 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: -6.5, y: 5.75, z: 10 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 6.5, y: 5.75, z: 20 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: -6.5, y: 5.75, z: 20 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 6.5, y: 5.75, z: 30 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: -6.5, y: 5.75, z: 30 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 6.5, y: 5.75, z: 40 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: -6.5, y: 5.75, z: 40 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -4, y: 5.75, z: 50 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 31, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 4, y: 5.75, z: 50 },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    // DYNAMIC
    createArrowEnemyConfig(-5.5, -35, Math.PI, 1),
    createArrowEnemyConfig(-6.5, -32.5, Math.PI, 1),
    createArrowEnemyConfig(-5.5, -30, Math.PI, 1),
    createArrowEnemyConfig(6.5, -32.5, Math.PI, 1),
    createArrowEnemyConfig(5.5, -30, Math.PI, 1),
    createArrowEnemyConfig(4.5, -5, Math.PI, 1),
    createArrowEnemyConfig(5.5, -10, Math.PI, 1),
    createArrowEnemyConfig(-4.5, -10, Math.PI, 1),
    createArrowEnemyConfig(-5.5, -10, Math.PI, 1),

    {
        trigger: { pool: { self: 1, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 0, y: 5.75, z: -11 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 1000,
            switch_shooter: { enabled: false },
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 1, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 0, y: 5.75, z: -21.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 1000,
            switch_shooter: { enabled: false },
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    //
    createArrowEnemyConfig(5.75, -10, 0, 2),
    createArrowEnemyConfig(4.25, -11.5, 0, 2),
    createArrowEnemyConfig(5.75, -13, 0, 2),
    createArrowEnemyConfig(4.25, -14.5, 0, 2),
    createArrowEnemyConfig(5.75, -16, 0, 2),
    createArrowEnemyConfig(4.25, -17.5, 0, 2),
    createArrowEnemyConfig(5.75, -19, 0, 2),
    createArrowEnemyConfig(4.25, -20.5, 0, 2),

    createArrowEnemyConfig(-5.75, -10, 0, 2),
    createArrowEnemyConfig(-4.25, -11.5, 0, 2),
    createArrowEnemyConfig(-5.75, -13, 0, 2),
    createArrowEnemyConfig(-4.25, -14.5, 0, 2),
    createArrowEnemyConfig(-5.75, -16, 0, 2),
    createArrowEnemyConfig(-4.25, -17.5, 0, 2),
    createArrowEnemyConfig(-5.75, -19, 0, 2),
    createArrowEnemyConfig(-4.25, -20.5, 0, 2),

    //
    createArrowEnemyConfig(1, 5, 0, 3),
    createArrowEnemyConfig(3, 5, 0, 3),
    createArrowEnemyConfig(5, 5, 0, 3),
    createArrowEnemyConfig(-1, 5, 0, 3),
    createArrowEnemyConfig(-3, 5, 0, 3),
    createArrowEnemyConfig(-5, 5, 0, 3),

    //
    createArrowEnemyConfig(1, 15, 0, 4),
    createArrowEnemyConfig(3, 15, 0, 4),
    createArrowEnemyConfig(5, 15, 0, 4),
    createArrowEnemyConfig(-1, 15, 0, 4),
    createArrowEnemyConfig(-3, 15, 0, 4),
    createArrowEnemyConfig(-5, 15, 0, 4),

    //
    createArrowEnemyConfig(1, 25, 0, 6),
    createArrowEnemyConfig(3, 25, 0, 6),
    createArrowEnemyConfig(5, 25, 0, 6),
    createArrowEnemyConfig(-1, 25, 0, 6),
    createArrowEnemyConfig(-3, 25, 0, 6),
    createArrowEnemyConfig(-5, 25, 0, 6),

    //
    createArrowEnemyConfig(3, 29, 0, 7),
    createArrowEnemyConfig(4, 32, 0, 7),
    createArrowEnemyConfig(5, 35, 0, 7),
    createArrowEnemyConfig(-3, 29, 0, 7),
    createArrowEnemyConfig(-4, 32, 0, 7),
    createArrowEnemyConfig(-5, 35, 0, 7),

    //
    createArrowEnemyConfig(1, 35, 0, 8),
    createArrowEnemyConfig(3, 35, 0, 8),
    createArrowEnemyConfig(5, 35, 0, 8),
    createArrowEnemyConfig(-1, 35, 0, 8),
    createArrowEnemyConfig(-3, 35, 0, 8),
    createArrowEnemyConfig(-5, 35, 0, 8),

    {
        trigger: { pool: { self: 8, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -4, y: 5.75, z: 45 }, rotation_y: Math.PI / 2, hp: 4 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },
    {
        trigger: { pool: { self: 8, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 4, y: 5.75, z: 45 }, rotation_y: -Math.PI / 2, hp: 4 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5.75, z: 60 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 100 },
    },
];
