import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

const HEIGHT = 20.5;
const SMALL_OFFSET = 0.2;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const createBoxLine = (
    x: number,
    zOffset: number = 0,
    zPositions: number[] = [-1.6, 0, 1.6],
): EnemyConfig[] => {
    const wh = 1.5;

    return zPositions.map((z) => ({
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x, y: 11, z: z + zOffset },
            rotation_y: Math.PI,
            hp: 3,
            spawn_animation: false,
            box: { w: 0.75, d: wh, h: wh },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    }));
};

export const enemies: EnemyConfig[] = [
    ...createBoxLine(-7, -10.9),
    ...createBoxLine(-7, 5.17),
    ...createBoxLine(-7, -3),
    ...createBoxLine(-7, 13.3),
    ...createBoxLine(-3, -24.61, [-0.8, 0.8]),

    {
        trigger: { pool: { self: 10, to_trigger: 301 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -11, y: 11.25, z: -3 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 2, d: 2, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 11, to_trigger: 300 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -4.12 - SMALL_OFFSET, y: 11.25, z: -19.37 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 11, to_trigger: 300 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -14.63 + SMALL_OFFSET, y: 11.25, z: -19.37 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 11, to_trigger: 300 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -14.63 + SMALL_OFFSET, y: 11.25, z: -29.63 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 11, to_trigger: 300 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -4.12 - SMALL_OFFSET, y: 11.25, z: -29.63 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 0, to_trigger: 999 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -9, y: 10.85, z: -24.61 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(3),
            spreading: 0.5,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 301,
            cooldown: 500,
            directions: generateDirections(1),
            spreading: 0.001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 300 },
        change_behavior: { follow_player_pool: 300 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_1"] },
        },
    },

    //
    {
        trigger: { pool: { self: 20, to_trigger: 101 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -11, y: 11.25, z: 5.17 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 2, d: 2, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 21, to_trigger: 100 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 1.62 + SMALL_OFFSET, y: 11.25, z: -6.38 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 21, to_trigger: 100 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 14.63 - SMALL_OFFSET, y: 11.25, z: -6.38 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 21, to_trigger: 100 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 14.63 - SMALL_OFFSET, y: 11.25, z: 4.13 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 21, to_trigger: 100 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 1.62 + SMALL_OFFSET, y: 11.25, z: 4.13 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 0, to_trigger: 999 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 8.3, y: 10.85, z: -1.21 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(3),
            spreading: 0.5,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
                [1, 0, 0],
            ],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 101,
            cooldown: 500,
            directions: generateDirections(1),
            spreading: 0.001,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
            ],
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 100 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_2"] },
        },
    },

    //
    {
        trigger: { pool: { self: 15, to_trigger: 201 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -11, y: 11.25, z: 13.75 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 2, d: 2, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 31, to_trigger: 200 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 1.62 + SMALL_OFFSET, y: 11.25, z: 11.12 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 31, to_trigger: 200 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 1.62 + SMALL_OFFSET, y: 11.25, z: 23.63 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 31, to_trigger: 200 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 14.63 - SMALL_OFFSET, y: 11.25, z: 23.63 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 31, to_trigger: 200 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: 14.63 - SMALL_OFFSET, y: 11.25, z: 11.12 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    {
        trigger: { pool: { self: 0, to_trigger: 999 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 8.3, y: 10.85, z: 17.19 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            directions: generateDirections(3),
            spreading: 0.5,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 201,
            cooldown: 500,
            directions: generateDirections(1),
            spreading: 0.001,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
            ],
        },
        shield: { enabled: true, pool: 200 },
        change_behavior: { follow_player_pool: 200 },
        sounds: {
            on_death: { engine: "voice", sound: ["robovoice_3"] },
        },
    },

    //
    {
        trigger: { pool: { self: 41, to_trigger: 500 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -8.12 - SMALL_OFFSET, y: 11.25, z: -17.13 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 41, to_trigger: 500 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -14.63 + SMALL_OFFSET, y: 11.25, z: -17.13 + SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },
    {
        trigger: { pool: { self: 41, to_trigger: 500 } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -14.63 + SMALL_OFFSET, y: 11.25, z: -8.62 - SMALL_OFFSET },
            rotation_y: Math.PI,
            hp: 2,
            spawn_animation: false,
            box: { w: 1, d: 1, h: 2 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        autoaimable: true,
    },

    // teachers
    {
        trigger: { pool: { self: 67, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -8.59, y: 11, z: -0.64 },
            rotation_y: Math.PI,
            hp: Infinity,
            spawn_animation: false,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 75,
            directions: [0],
            spreading: 0.001,
            pattern: [[1, 1, 0]],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 500,
            cooldown: Infinity,
            directions: [0],
            spreading: 0.001,
            pattern: [[1, 1, 0]],
        },
    },
    {
        trigger: { pool: { self: 67, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -8.59, y: 11, z: 7.89 },
            rotation_y: Math.PI,
            hp: Infinity,
            spawn_animation: false,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 75,
            directions: [0],
            spreading: 0.001,
            pattern: [[1, 0, 0]],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 500,
            cooldown: Infinity,
            directions: [0],
            spreading: 0.001,
            pattern: [[1, 0, 0]],
        },
    },
    {
        trigger: { pool: { self: 67, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: -8.59, y: 11, z: 16.37 },
            rotation_y: Math.PI,
            hp: Infinity,
            spawn_animation: false,
            box: { w: 1.5, d: 1.5, h: 1.5 },
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 75,
            directions: [0],
            spreading: 0.001,
            pattern: [[0, 1, 0]],
        },
        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 500,
            cooldown: Infinity,
            directions: [0],
            spreading: 0.001,
            pattern: [[0, 1, 0]],
        },
    },

    //
    {
        trigger: { pool: { self: 69, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -11, y: 10.85, z: 21.4 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 3.0 },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 999 },
    },
];
