import { WallConfig } from "types/static/Wall.types";

import { WALLS_COLOR } from "core_constants";

export const walls: WallConfig[] = [
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: -24 },
        size: { w: 150, h: 1, d: 4.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 29.25 },
        size: { w: 150, h: 1, d: 4.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 4.25 },
        size: { w: 45, h: 1, d: 4.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 4.25 },
        size: { w: 45, h: 1, d: 4.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 0, y: 5.45, z: 0 },
        size: { w: 66.25, h: 1, d: 4.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -17.5, y: 5.45, z: -6 },
        size: { w: 15, h: 1, d: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 17.5, y: 5.45, z: -6 },
        size: { w: 15, h: 1, d: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -17.5, y: 5.45, z: -18 },
        size: { w: 15, h: 1, d: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 17.5, y: 5.45, z: -18 },
        size: { w: 15, h: 1, d: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -41.15, y: 5.45, z: 49 },
        size: { w: 8.5, h: 1, d: 102.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 41.15, y: 5.45, z: 49 },
        size: { w: 8.5, h: 1, d: 102.4 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    //
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -21.56, y: 5.45, z: 8.5 },
        size: { w: 23.13, h: 1, d: 13.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 21.56, y: 5.45, z: 8.5 },
        size: { w: 23.13, h: 1, d: 13.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -23.54, y: 5.45, z: 25.23 },
        size: { w: 27.1, h: 1, d: 12.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 23.54, y: 5.45, z: 25.23 },
        size: { w: 27.1, h: 1, d: 12.45 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },

    //
    {
        trigger: { pool: 1, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -17.5, y: 5.45, z: -12.9 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 1, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -17.5, y: 5.45, z: -11.1 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 1, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 17.5, y: 5.45, z: -12.9 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 1, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 17.5, y: 5.45, z: -11.1 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    //
    {
        trigger: { pool: 2, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 34.1, y: 5.45, z: -1.45 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 2, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 35.9, y: 5.45, z: -1.45 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 2, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -34.1, y: 5.45, z: -1.45 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 2, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -35.9, y: 5.45, z: -1.45 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    //
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: 47.5, y: 5.45, z: 25 },
        size: { w: 4.4, h: 1, d: 150 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    {
        trigger: { pool: 0, spawn: { on_start: true, on_update: false } },
        type: "box",
        position: { x: -47.5, y: 5.45, z: 25 },
        size: { w: 4.4, h: 1, d: 150 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
    },
    //
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: -32.35, y: 5.45, z: 18.05 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: -32.35, y: 5.45, z: 16.25 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: 32.35, y: 5.45, z: 18.05 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
    {
        trigger: { pool: 3, spawn: { on_start: false, on_update: true } },
        type: "box",
        position: { x: 32.35, y: 5.45, z: 16.25 },
        size: { w: 1.5, h: 1.5, d: 1.5 },
        rotation: { x: 0, y: 0, z: 0 },
        color: WALLS_COLOR,
        solid: true,
        is_lava: false,
        effective: true,
    },
];
