export const REFERENCE_WIDTH = 2560;
export const REFERENCE_HEIGHT = 1440;

export const PRIMARY_COLOR_LIGHT = { r: 0.71, g: 0.67, b: 0.53, a: 1.0 };
export const PRIMARY_COLOR_DARK = { r: 0.24, g: 0.23, b: 0.19, a: 1.0 };

export const GROUND_COLOR = { r: 0.71, g: 0.67, b: 0.53, a: 1.0 };
export const WALLS_COLOR = { r: 0.8, g: 0.77, b: 0.69, a: 1.0 };

export const LS_KEYS = {
    GENERAL_VOLUME: "HACK_COMPLETE_AUDIO_GENERAL_VOLUME",
    SFX_VOLUME: "HACK_COMPLETE_AUDIO_SFX_VOLUME",
    MUSIC_VOLUME: "HACK_COMPLETE_AUDIO_MUSIC_VOLUME",
    VOICE_VOLUME: "HACK_COMPLETE_AUDIO_VOICE_VOLUME",
    RADIO_SETTING: "HACK_COMPLETE_RADIO_SETTING",
    DIFFICULTY: "HACK_COMPLETE_DIFFICULTY",
    VERSE_PROGRESS: "HACK_COMPLETE_VERSE_PROGRESS",
    UNLOCK_ALL_VERSES: "HACK_COMPLETE_UNLOCK_ALL_VERSES",
    PHYSICS_SUBSTEPS: "HACK_COMPLETE_PHYSICS_SUBSTEPS",
};
