import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";

import { generateDirections } from "utils/math";

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 1, to_trigger: 2 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 4, y: 5.65, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: 3 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 6, y: 5.65, z: 0 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 3, to_trigger: 4 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 4, y: 5.65, z: -6 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 4, to_trigger: 100 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 4, y: 5.65, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 200,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 5, to_trigger: 6 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -4, y: 5.65, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 6, to_trigger: 7 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -6, y: 5.65, z: 0 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 1500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 7, to_trigger: 8 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -4, y: 5.65, z: -6 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.5 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 8, to_trigger: 100 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -4, y: 5.65, z: 6 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1500,
            cooldown: 200,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 5.65, z: 2 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: Math.PI / 2 },
        animation: { enabled: false },
        shooter: { enabled: false },
        rage: {
            enabled: true,
            pool: 100,
            initial_delay: 1000,
            cooldown: 250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(1),
        },
        shield: { enabled: true, pool: 100 },
        change_behavior: { follow_player_pool: 100 },
    },
];
