import { EnemyConfig } from "types/enemy/Enemies.types";

const HEIGHT = 20.5;

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 1, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: { position: { x: 0, y: 10.85, z: 0 }, rotation_y: Math.PI, hp: 3, delay: 0.2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    //
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -11, y: 10.85, z: 8 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 11, y: 10.85, z: 8 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -7, y: 10.85, z: 8 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 7, y: 10.85, z: 8 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -9, y: 10.85, z: 5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 9, y: 10.85, z: 5 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -2.5, y: 10.85, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 100 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2.5, y: 10.85, z: 10 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 0, y: 10.85, z: 10 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: HEIGHT },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 100,
            cooldown_dynamic: [0, 200, 400, 600, 800, 1000],
            directions: [0, Math.PI / 4, -Math.PI / 4],
            spreading: 0.0001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
            switch_shooter: { enabled: true, delay: [300, 1000] },
        },
        shield: { enabled: true, pool: 100 },
    },
];
