import { EnemyConfig } from "types/enemy/Enemies.types";

import { SURFACE_SETTINGS } from "./settings";
import { generateDirections } from "utils/math";

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

const createBoxLineX = (
    z: number,
    xOffset: number,
    xPositions: number[],
    size?: number,
): EnemyConfig[] => {
    const wh = size ?? 1.45;

    return xPositions.map((x) => ({
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x: x + xOffset, y: 5.75, z },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: wh, d: 0.75, h: wh },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    }));
};

const createBoxLineZ = (x: number, zOffset: number, xPositions: number[]): EnemyConfig[] => {
    const wh = 1.45;

    return xPositions.map((z) => ({
        trigger: { pool: { self: 5, to_trigger: null } },
        enemy_type: "box",
        on_spawn: {
            position: { x, y: 5.75, z: z + zOffset },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
            box: { w: 0.75, d: wh, h: wh },
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
    }));
};

export const enemies: EnemyConfig[] = [
    ...createBoxLineX(5, -29.1, [-3.2, -1.6, 0, 1.6, 3.2]),
    ...createBoxLineZ(-19.65, 19.9, [-1.6, 0, 1.6]),
    ...createBoxLineZ(-19.65, 34.9, [-1.6, 0, 1.6]),
    ...createBoxLineX(43.25, 14.5, [-3.5, -1.75, 0, 1.75, 3.5], 1.5),

    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: 12.5, y: 5.65, z: -1.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: 1000,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 0, to_trigger: null } },
        enemy_type: "cylinder-shield",
        on_spawn: { position: { x: -38.5, y: 5.65, z: -1.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 1000,
            cooldown: 1000,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 1, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -38.5, y: 5.65, z: 18 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },
    {
        trigger: { pool: { self: 1, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -38.5, y: 5.65, z: 32 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },

    {
        trigger: { pool: { self: 1, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -25, y: 5.65, z: 18 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },
    {
        trigger: { pool: { self: 1, to_trigger: null } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: -25, y: 5.65, z: 32 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        rocket_launcher: { enabled: true, cooldown: 1000 },
    },

    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2.5, y: 5.65, z: 21.5 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 2.5, y: 5.65, z: 19 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 11, y: 5.65, z: 30 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 13.3, y: 5.65, z: 30 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 15.6, y: 5.65, z: 30 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 2, to_trigger: null } },
        enemy_type: "arrow",
        on_spawn: { position: { x: 18, y: 5.65, z: 30 }, rotation_y: Math.PI, hp: 2 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(250, 500),
            cooldown: getRandomCooldown(500, 1000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.2,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 4, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 5, y: 5.65, z: 47.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 4, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 23, y: 5.65, z: 47.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 4, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 5, y: 5.65, z: 56.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -1.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 4, to_trigger: 100 } },
        enemy_type: "cylinder",
        on_spawn: { position: { x: 23, y: 5.65, z: 56.5 }, rotation_y: Math.PI, hp: 4 },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 1.0 },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: getRandomCooldown(500, 1000),
            cooldown: 750,
            pattern: [
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 1, 0],
            ],
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    // CORE
    {
        trigger: { pool: { self: 10, to_trigger: 1000 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 14.5, y: 5.65, z: 55 },
            rotation_y: Math.PI / 2,
            hp: 5,
        },
        ground: { id: 0, physics: "plane", size: SURFACE_SETTINGS.h },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: true, angular_speed: 3.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 500,
            cooldown: 500,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.0001,
            directions: [0],
        },
        shield: { enabled: true, pool: 100 },
    },
];
