import { EnemyConfig } from "types/enemy/Enemies.types";
import { generateDirections } from "utils/math";

const CHEER_PATTERN_RAGED: [number, number, number][] = Array(4).fill([1, 1, 0]);
const CHEER_PATTERN_FRIENDLY: [number, number, number][] = Array(20).fill([0, 0, 1]);

function getRandomCooldown(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function createCircleEnemiesRange(count: number, step: number): EnemyConfig[] {
    return Array.from({ length: count }, (_, i) => i * step).map((from, index) => ({
        trigger: { pool: { self: 500, to_trigger: 1000 } },
        enemy_type: "sphere",

        on_spawn: {
            position: { x: 97, y: 5.75, z: 133 },
            rotation_y: 0,
            hp: 5,
            spawn_animation: false,
        },

        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,

        follow_player: { enabled: false },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false },

        auto_rotation: { enabled: true, angular_speed: 0.5 },

        animation: {
            enabled: true,
            name: "circle",
            params: {
                plane: "xz",
                radius: 10,
                speed: 100,
                frames: 1000,
                from,
            },
        },

        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 750,
            directions: generateDirections(4),
            spreading: 0.001,
            pattern: [
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
                [1, 1, 0],
            ],
        },

        rage: {
            enabled: false,
            initial_delay: 250,
            pool: 600,
            cooldown: 5000,
            directions: generateDirections(1),
            spreading: 0.001,
            pattern: [
                [1, 0, 0],
                [1, 0, 0],
            ],
        },
    }));
}

export const enemies: EnemyConfig[] = [
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 7, y: 5.75, z: -8 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -7, y: 5.75, z: -8 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 7, y: 5.75, z: 0 }, rotation_y: 0, hp: 2, delay: 0.3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -7, y: 5.75, z: 0 }, rotation_y: 0, hp: 2, delay: 0.3 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 7, y: 5.75, z: 8 }, rotation_y: 0, hp: 2, delay: 0.6 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -7, y: 5.75, z: 8 }, rotation_y: 0, hp: 2, delay: 0.6 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 7, y: 5.75, z: 16 }, rotation_y: 0, hp: 2, delay: 0.9 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -7, y: 5.75, z: 16 }, rotation_y: 0, hp: 2, delay: 0.9 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 7, y: 5.75, z: 24 }, rotation_y: 0, hp: 2, delay: 1.2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 0, to_trigger: 10 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: -7, y: 5.75, z: 24 }, rotation_y: 0, hp: 2, delay: 1.2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.5 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    // LEFT ROOM
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -20, y: 5.75, z: 40 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -30, y: 5.75, z: 35 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -30, y: 5.75, z: 40 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow",
        on_spawn: { position: { x: -30, y: 5.75, z: 45 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2.0 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 2.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: getRandomCooldown(1000, 2000),
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 0, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -45, y: 5.75, z: 36 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 350,
            cooldown: 350,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -45, y: 5.75, z: 38 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 300,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -45, y: 5.75, z: 40 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -45, y: 5.75, z: 42 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 300,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 101, to_trigger: 105 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: -45, y: 5.75, z: 44 }, rotation_y: Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 350,
            cooldown: 350,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 100, to_trigger: 250 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: -45, y: 5.75, z: 39.75 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false, angular_speed: 0.5 },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 105 },
    },

    // RIGHT ROOM
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 12.5, y: 5.75, z: 33.63 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 20.5, y: 5.75, z: 33.63 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 28.5, y: 5.75, z: 33.63 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 36.5, y: 5.75, z: 33.63 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 44.5, y: 5.75, z: 33.63 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 12.5, y: 5.75, z: 45.88 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 20.5, y: 5.75, z: 45.88 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 28.5, y: 5.75, z: 45.88 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 36.5, y: 5.75, z: 45.88 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },
    {
        trigger: { pool: { self: 400, to_trigger: 20 } },
        enemy_type: "cheer",
        on_spawn: { position: { x: 44.5, y: 5.75, z: 45.88 }, rotation_y: 0, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: 0.5 },
        animation: { enabled: false },
        reflection: { enabled: true, by_hp: false, time: 0.5 },
        shooter: {
            enabled: true,
            initial_delay: 0,
            cooldown: 250,
            pattern: CHEER_PATTERN_RAGED,
            spreading: 0.001,
            directions: generateDirections(2),
        },
    },

    {
        trigger: { pool: { self: 20, to_trigger: 69 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 59, y: 5.75, z: 34 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 300,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 69 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 59, y: 5.75, z: 40 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 250,
            cooldown: 250,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },
    {
        trigger: { pool: { self: 20, to_trigger: 69 } },
        enemy_type: "arrow-shield",
        on_spawn: { position: { x: 59, y: 5.75, z: 46 }, rotation_y: -Math.PI / 2, hp: 2 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 2 },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: true, angular_speed: 1.0 },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: {
            enabled: true,
            initial_delay: 300,
            cooldown: 300,
            switch_shooter: { enabled: false, delay: [500, 100] },
            pattern: [[1, 1, 0]],
            spreading: 0.001,
            directions: [0],
        },
    },

    {
        trigger: { pool: { self: 410, to_trigger: 142 } },
        enemy_type: "sphere",
        on_spawn: {
            position: { x: 64, y: 5.75, z: 39.75 },
            rotation_y: Math.PI,
            hp: 5,
            spawn_animation: false,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: true, speed: 0.0 },
        triggers_by_player: [false, false],
        rotate_to_player: { enabled: false, angular_speed: 0.5 },
        auto_rotation: { enabled: true },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 69 },
    },

    // BOMBS
    {
        trigger: { pool: { self: 142, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 97.0, y: 5.75, z: 128 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 142, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 97.0, y: 5.75, z: 138 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 142, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 102.0, y: 5.75, z: 133 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },
    {
        trigger: { pool: { self: 142, to_trigger: null } },
        enemy_type: "cylinder-bomb",
        on_spawn: {
            position: { x: 92.0, y: 5.75, z: 133 },
            rotation_y: Math.PI,
            hp: 3,
        },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: true, angular_speed: -0.33 },
        animation: { enabled: false },
        shooter: { enabled: false },
    },

    // DISABLER
    {
        trigger: { pool: { self: 300, to_trigger: 600 } },
        enemy_type: "sphere",
        on_spawn: { position: { x: 32.5, y: 5.75, z: 73 }, rotation_y: 0, hp: 5 },
        ground: { id: 0, physics: "plane", size: 10 },
        is_inside_ground: false,
        follow_player: { enabled: false },
        triggers_by_player: [true, false],
        rotate_to_player: { enabled: false },
        auto_rotation: { enabled: false },
        animation: { enabled: false },
        shooter: { enabled: false },
        shield: { enabled: true, pool: 250 },
    },

    // CAROUSEL
    ...createCircleEnemiesRange(10, 100),
];
